import { Injectable, signal } from '@angular/core';
import { TRADUCOES_ES } from './traducoes-es';

export type Idioma = 'pt' | 'en' | 'es';

type Traducao = { pt: string; en: string };

const TRADUCOES: Record<string, Traducao> = {
  // Navegação / header
  'nav.platform': { pt: 'Plataforma', en: 'Platform' },
  'nav.solutions': { pt: 'Soluções', en: 'Solutions' },
  'nav.industries': { pt: 'Indústrias', en: 'Industries' },
  'nav.modules': { pt: 'Módulos', en: 'Modules' },
  'nav.features': { pt: 'Recursos', en: 'Features' },
  'nav.pricing': { pt: 'Planos', en: 'Pricing' },
  'header.signin': { pt: 'Entrar', en: 'Sign in' },
  'header.bookDemo': { pt: 'Agende uma demo', en: 'Book a demo' },
  'header.toEN': { pt: 'Mudar para English', en: 'Switch to English' },
  'header.toPT': { pt: 'Mudar para Português', en: 'Switch to Português' },
  'header.toES': { pt: 'Mudar para Español', en: 'Switch to Español' },

  // Shell operacional
  'shell.modules': { pt: 'Módulos do Sistema', en: 'System Modules' },
  'shell.dashboard': { pt: 'Dashboard', en: 'Dashboard' },
  'shell.units': { pt: 'Unidades & Responsáveis', en: 'Units & Owners' },
  'shell.vault': { pt: 'Cofre Digital & OCR', en: 'Digital Vault & OCR' },
  'shell.assets': { pt: 'Gestão de Ativos & QR', en: 'Asset & QR Management' },
  'shell.alerts': { pt: 'Alertas Inteligentes', en: 'Smart Alerts' },
  'shell.inspection': { pt: 'Modo Fiscalização', en: 'Inspection Mode' },
  'shell.roi': { pt: 'Relatório de ROI', en: 'ROI Report' },
  'shell.operational': { pt: 'Licenfy Operacional', en: 'Licenfy Operations' },
  'shell.allUnits': { pt: 'Todas as Unidades', en: 'All Units' },
  'shell.inspectionBtn': { pt: 'Fiscalização', en: 'Inspection' },
  'shell.logoutBtn': { pt: 'Sair', en: 'Sign out' },
  'shell.unitsShort': { pt: 'Unidades & Hierarquia', en: 'Units & Hierarchy' },

  // Auth
  'auth.back': { pt: 'Voltar ao site', en: 'Back to site' },
  'auth.loginTab': { pt: 'Entrar com conta criada', en: 'Sign in with existing account' },
  'auth.signupTab': { pt: 'Testar / Criar conta', en: 'Try / Create account' },
  'auth.welcomeBack': { pt: 'BEM-VINDO DE VOLTA', en: 'WELCOME BACK' },
  'auth.loginTitle': { pt: 'Entre na sua conta', en: 'Sign in to your account' },
  'auth.loginSub': { pt: 'Acesse o painel da sua empresa com sua conta já cadastrada.', en: 'Access your company dashboard with your existing account.' },
  'auth.email': { pt: 'E-mail corporativo', en: 'Work email' },
  'auth.password': { pt: 'Senha', en: 'Password' },
  'auth.loginBtn': { pt: 'Entrar na plataforma', en: 'Sign in to platform' },
  'auth.authenticating': { pt: 'Autenticando...', en: 'Signing in...' },
  'auth.forgot': { pt: 'Esqueci minha senha', en: 'Forgot my password' },
  'auth.noAccount': { pt: 'Ainda não tem uma conta?', en: "Don't have an account yet?" },
  'auth.seePlans': { pt: 'Conheça nossos planos e assine', en: 'View our plans and subscribe' },
  'auth.createTest': { pt: 'Crie uma conta de teste', en: 'Create a trial account' },
  'auth.getStarted': { pt: 'COMECE AGORA', en: 'GET STARTED' },
  'auth.signupTitle': { pt: 'Crie sua conta de teste', en: 'Create your trial account' },
  'auth.signupSub': { pt: 'Experimente o Licenfy de imediato — sem necessidade de banco de dados.', en: 'Try Licenfy right away — no database required.' },
  'auth.name': { pt: 'Nome completo', en: 'Full name' },
  'auth.createPass': { pt: 'Crie uma senha', en: 'Create a password' },
  'auth.confirmPass': { pt: 'Confirme sua senha', en: 'Confirm your password' },
  'auth.signupBtn': { pt: 'Criar conta e acessar plataforma', en: 'Create account and open platform' },
  'auth.haveAccount': { pt: 'Já tem uma conta?', en: 'Already have an account?' },
  'auth.signinLink': { pt: 'Entrar', en: 'Sign in' },
  'auth.lgpd': { pt: 'Li e concordo com os Termos de Uso e a Política de Privacidade, e autorizo o tratamento dos meus dados conforme a LGPD (Lei nº 13.709/2018).', en: 'I have read and agree to the Terms of Use and Privacy Policy, and I consent to the processing of my data under the LGPD (Law No. 13,709/2018).' },
  'auth.needLogin': { pt: 'Para entrar, é necessário aceitar os Termos de Uso e a Política de Privacidade (LGPD).', en: 'To sign in, you must accept the Terms of Use and Privacy Policy (LGPD).' },
  'auth.needSignup': { pt: 'Para criar a conta, é necessário aceitar os Termos de Uso e a Política de Privacidade (LGPD).', en: 'To create your account, you must accept the Terms of Use and Privacy Policy (LGPD).' },

  // Landing — hero e seções
  'landing.heroKicker': { pt: 'REGULARIDADE OPERACIONAL EM TEMPO REAL', en: 'REAL-TIME OPERATIONAL COMPLIANCE' },
  'landing.heroTitle': { pt: 'Nunca mais seja interditado por um alvará que venceu sem avisar', en: 'Never get shut down again by an expired permit' },
  'landing.heroSub': { pt: 'O Licenfy centraliza suas licenças, alvarás e ativos com monitoramento contínuo e alertas que escalam por e-mail corporativo — do time local até a diretoria.', en: 'Licenfy centralizes your licenses, permits and assets with continuous monitoring and escalating corporate email alerts — from the local team to the board.' },
  'landing.trust1': { pt: 'Zero risco de interdição nas filiais', en: 'Zero shutdown risk across branches' },
  'landing.trust2': { pt: 'OCR de alvarás em PDF — meta de 99%+ de precisão', en: 'PDF permit OCR — 99%+ accuracy goal' },
  'landing.trust3': { pt: 'Pronto para redes com 1 a 100+ unidades', en: 'Ready for networks with 1 to 100+ units' },
  'landing.platformKicker': { pt: 'PLATAFORMA LICENFY', en: 'LICENFY PLATFORM' },
  'landing.platformTitle': { pt: 'Uma única visão para cada prazo, documento e ativo.', en: 'A single view for every deadline, document and asset.' },
  'landing.platformSub': { pt: 'Troque arquivos espalhados e planilhas manuais por uma operação conectada, com contexto por unidade e histórico pronto para auditorias.', en: 'Replace scattered files and manual spreadsheets with a connected operation, per-unit context and audit-ready history.' },
  'landing.solKicker': { pt: 'SOLUÇÕES PARA A SUA OPERAÇÃO', en: 'SOLUTIONS FOR YOUR OPERATION' },
  'landing.solTitle': { pt: 'Controle que acompanha o ritmo do seu negócio.', en: 'Control that keeps up with your business.' },
  'landing.plansKicker': { pt: 'PLANOS', en: 'PRICING' },
  'landing.plansTitle': { pt: 'Um plano simples para cada ritmo de operação', en: 'A simple plan for every pace of operation' },
  'landing.plansSub': { pt: 'Sem taxa de implantação. Cancele quando quiser no mensal. No anual, você economiza 50%.', en: 'No setup fee. Cancel anytime on monthly. Save 50% on annual.' },
  'landing.monthly': { pt: 'Mensal', en: 'Monthly' },
  'landing.annual': { pt: 'Anual', en: 'Annual' },
  'landing.roiBadge': { pt: 'RETORNO SOBRE INVESTIMENTO', en: 'RETURN ON INVESTMENT' },
  'landing.roiTitle': { pt: 'O custo de uma única interdição paga 10 anos de Licenfy', en: 'The cost of a single shutdown pays for 10 years of Licenfy' },

  // Módulos — cabeçalhos
  'mod.dashboardTitle': { pt: 'Dashboard', en: 'Dashboard' },
  'mod.unitsTitle': { pt: 'Unidades & Hierarquia', en: 'Units & Hierarchy' },
  'mod.vaultTitle': { pt: 'Cofre Digital & OCR', en: 'Digital Vault & OCR' },
  'mod.assetsTitle': { pt: 'Gestão de Ativos & QR', en: 'Asset & QR Management' },
  'mod.notifTitle': { pt: 'Notificações Inteligentes por E-mail Corporativo', en: 'Smart Corporate Email Notifications' },
  'mod.notifSub': { pt: 'Alertas de vencimento programados (90, 60, 30 e 7 dias) enviados com formalidade jurídica e corporativa aos gestores, compliance e diretoria.', en: 'Scheduled expiration alerts (90, 60, 30 and 7 days) sent with legal and corporate formality to managers, compliance and the board.' },
  'mod.inspectionTitle': { pt: 'Modo Fiscalização', en: 'Inspection Mode' },
  'mod.roiTitle': { pt: 'Relatório de ROI', en: 'ROI Report' },

  // Landing — conteúdo
  'landing.platformPoint1Title': { pt: 'Operação conectada', en: 'Connected operations' },
  'landing.platformPoint1Desc': { pt: 'Licenças, pessoas e ativos no mesmo fluxo.', en: 'Licenses, people and assets in one workflow.' },
  'landing.platformPoint2Title': { pt: 'Visão por unidade', en: 'Unit-level visibility' },
  'landing.platformPoint2Desc': { pt: 'Priorize a ação certa em cada filial.', en: 'Prioritize the right action at every branch.' },
  'landing.platformPoint3Title': { pt: 'Histórico auditável', en: 'Auditable history' },
  'landing.platformPoint3Desc': { pt: 'Decisões e documentos sempre rastreáveis.', en: 'Decisions and documents always traceable.' },
  'landing.solutionsTitle': { pt: 'Controle que acompanha o ritmo do seu negócio.', en: 'Control that keeps up with your business.' },
  'landing.solution1Title': { pt: 'Redes e franquias', en: 'Networks and franchises' },
  'landing.solution1Desc': { pt: 'Padronize a conformidade de cada unidade, sem sobrecarregar o time central.', en: 'Standardize compliance across every unit without overloading the central team.' },
  'landing.solution2Title': { pt: 'Jurídico e regularidade', en: 'Legal and compliance' },
  'landing.solution2Desc': { pt: 'Antecipe riscos e mantenha evidências organizadas para fiscalizações.', en: 'Anticipate risks and keep evidence organized for inspections.' },
  'landing.solution3Title': { pt: 'Facilities e operações', en: 'Facilities and operations' },
  'landing.solution3Desc': { pt: 'Conecte obrigações regulatórias à manutenção dos ativos físicos.', en: 'Connect regulatory obligations to physical asset maintenance.' },
  'landing.industriesTitle': { pt: 'O Licenfy atende diversos setores', en: 'Licenfy serves multiple industries' },
  'landing.industry1': { pt: 'Indústria leve', en: 'Light industry' },
  'landing.industry1Desc': { pt: 'Ambiental, ativos e manutenção', en: 'Environmental, assets and maintenance' },
  'landing.industry2': { pt: 'Saúde', en: 'Healthcare' },
  'landing.industry2Desc': { pt: 'Farmácias e clínicas', en: 'Pharmacies and clinics' },
  'landing.industry3': { pt: 'Varejo multi-loja', en: 'Multi-store retail' },
  'landing.industry3Desc': { pt: 'Redes de 5 a 50 unidades', en: 'Networks of 5 to 50 units' },
  'landing.industry4': { pt: 'Alimentação', en: 'Food service' },
  'landing.industry4Desc': { pt: 'Restaurantes e food service', en: 'Restaurants and food service' },
  'landing.featuresTitle': { pt: 'Da gaveta ao controle absoluto em 4 pilares', en: 'From the filing cabinet to complete control in 4 pillars' },
  'landing.featuresSub': { pt: 'O fim do pesadelo das planilhas esquecidas, multas municipais e surpresas na hora da fiscalização.', en: 'The end of forgotten spreadsheets, municipal fines and surprises during inspections.' },
  'landing.feature1Title': { pt: 'Cofre Digital & OCR Automatizado', en: 'Digital Vault & Automated OCR' },
  'landing.feature1Desc': { pt: 'Basta arrastar o PDF do alvará. O sistema de OCR lê e cataloga automaticamente órgão emissor, datas de emissão e vencimento, além de condicionantes técnicas.', en: 'Just drag the permit PDF. OCR automatically reads and catalogs the issuing body, issue and expiration dates, and technical requirements.' },
  'landing.feature1Cta': { pt: 'Explorar Cofre Digital', en: 'Explore Digital Vault' },
  'landing.feature2Title': { pt: 'Modo Fiscalização', en: 'Inspection Mode' },
  'landing.feature2Desc': { pt: 'O fiscal da prefeitura ou bombeiro chegou de surpresa na filial? Em 1 clique você gera o dossiê oficial consolidado com QR Code público de autenticidade para apresentar no balcão.', en: 'A city or fire inspection arrived unannounced? Generate the consolidated official dossier with a public verification QR code in one click.' },
  'landing.feature2Cta': { pt: 'Ver Dossiê em Ação', en: 'See the Dossier in Action' },
  'landing.feature3Title': { pt: 'Ativos Físicos com QR Code', en: 'Physical Assets with QR Code' },
  'landing.feature3Desc': { pt: 'Gere etiquetas para colar em extintores, elevadores, geradores e ar-condicionado. A equipe local aponta a câmera do celular e confere a validade da recarga sem login.', en: 'Generate labels for extinguishers, elevators, generators and air conditioning. Local teams scan with a phone and check recharge validity without logging in.' },
  'landing.feature3Cta': { pt: 'Ver Gestão de Ativos', en: 'View Asset Management' },
  'landing.feature4Title': { pt: 'Alertas Inteligentes', en: 'Smart Alerts' },
  'landing.feature4Desc': { pt: 'Dispare notificações automáticas por e-mail para o gerente da unidade, responsáveis e diretoria com 90, 60 e 30 dias de antecedência. Garanta governança com trilha de auditoria.', en: 'Send automatic email notifications to unit managers, owners and leadership 90, 60 and 30 days in advance. Keep governance with an audit trail.' },
  'landing.feature4Cta': { pt: 'Configurar Alertas', en: 'Configure Alerts' },
  'landing.resourcesKicker': { pt: 'RECURSOS', en: 'FEATURES' },
  'landing.resourcesTitle': { pt: 'Informação pronta quando a operação precisa agir.', en: 'Information ready when operations need to act.' },
  'landing.resourcesSub': { pt: 'Mais previsibilidade para decisões diárias e respostas rápidas em qualquer cenário.', en: 'More predictability for daily decisions and fast responses in any scenario.' },
  'landing.resource1Title': { pt: 'Leitura de documentos por OCR', en: 'Document reading with OCR' },
  'landing.resource1Desc': { pt: 'Extração automática de campos e datas de validade.', en: 'Automatic extraction of fields and expiration dates.' },
  'landing.resource2Title': { pt: 'Alertas escalonados', en: 'Escalating alerts' },
  'landing.resource2Desc': { pt: 'Notificações por prazo para os responsáveis certos.', en: 'Deadline notifications to the right people.' },
  'landing.resource3Title': { pt: 'QR Code para ativos', en: 'QR Code for assets' },
  'landing.resource3Desc': { pt: 'Consulta imediata da situação no local da operação.', en: 'Immediate status lookup at the operating location.' },
  'landing.roiSubtitle': { pt: 'Empresas que utilizam o Licenfy reduzem a zero o índice de multas e economizam milhares de horas de trabalho operacional do jurídico e de facilities.', en: 'Companies using Licenfy reduce fines to zero and save thousands of hours of legal and facilities work.' },
  'landing.roiLabel1': { pt: 'Economia acumulada gerada na plataforma', en: 'Accumulated savings generated on the platform' },
  'landing.roiLabel2': { pt: 'Autuações pendentes nas unidades monitoradas', en: 'Pending violations at monitored units' },
  'landing.roiLabel3': { pt: 'Score médio de conformidade nas unidades monitoradas', en: 'Average compliance score at monitored units' },
  'landing.monthlyHeadline': { pt: 'Flexibilidade mês a mês', en: 'Month-to-month flexibility' },
  'landing.monthlyDesc': { pt: 'Ideal para validar o Licenfy em poucas unidades e expandir no seu ritmo.', en: 'Ideal for validating Licenfy across a few units and scaling at your own pace.' },
  'landing.monthlyNote': { pt: 'Cobrança mensal recorrente. Sem fidelidade.', en: 'Recurring monthly billing. No commitment.' },
  'landing.monthlyFeature1': { pt: 'Licenças, alvarás e ativos ilimitados', en: 'Unlimited licenses, permits and assets' },
  'landing.monthlyFeature2': { pt: 'OCR de PDFs com extração automática', en: 'PDF OCR with automatic extraction' },
  'landing.monthlyFeature3': { pt: 'Alertas por e-mail em 90, 60 e 30 dias', en: 'Email alerts at 90, 60 and 30 days' },
  'landing.monthlyFeature4': { pt: 'QR Code para ativos e Modo Fiscalização', en: 'QR Code for assets and Inspection Mode' },
  'landing.monthlyCta': { pt: 'Começar no mensal', en: 'Start monthly' },
  'landing.saveTag': { pt: 'ECONOMIZE 50%', en: 'SAVE 50%' },
  'landing.annualHeadline': { pt: 'Melhor custo-benefício', en: 'Best value' },
  'landing.annualDesc': { pt: 'Para operações que querem previsibilidade e máxima economia o ano todo.', en: 'For operations that want predictability and maximum savings all year.' },
  'landing.annualNote': { pt: 'Equivale a', en: 'Equivalent to' },
  'landing.annualNoteRest': { pt: '— 12 meses pelo preço de 6.', en: '— 12 months for the price of 6.' },
  'landing.annualFeature1': { pt: 'Tudo do plano Mensal incluído', en: 'Everything in the Monthly plan included' },
  'landing.annualFeature2': { pt: '2 meses de prioridade no suporte', en: '2 months of priority support' },
  'landing.annualFeature3': { pt: 'Relatório executivo de conformidade', en: 'Executive compliance report' },
  'landing.annualFeature4': { pt: 'Onboarding assistido das unidades', en: 'Assisted unit onboarding' },
  'landing.annualCta': { pt: 'Assinar o anual', en: 'Subscribe annually' },
  'landing.footerKicker': { pt: 'CONFORMIDADE EM MOVIMENTO', en: 'COMPLIANCE IN MOTION' },
  'landing.footerTitle': { pt: 'Controle total. Comece agora.', en: 'Complete control. Start now.' },
  'landing.footerSub': { pt: 'Transforme licenças, alvarás e ativos em uma operação segura e previsível.', en: 'Turn licenses, permits and assets into a safe, predictable operation.' },
  'landing.footerDesc': { pt: 'A plataforma definitiva de conformidade regulatória, gestão de alvarás e ativos com tecnologia de ponta para médias e grandes empresas.', en: 'The definitive regulatory compliance, permit and asset management platform with advanced technology for medium and large companies.' },
  'landing.encryption': { pt: 'Criptografia Bancária', en: 'Bank-grade encryption' },
  'landing.contact': { pt: 'Contato & Demonstração', en: 'Contact & Demo' },
  'landing.scheduleConsultant': { pt: 'Agendar com Consultor', en: 'Schedule with a consultant' },
  'landing.terms': { pt: 'Termos de Uso', en: 'Terms of Use' },
  'landing.privacy': { pt: 'Política de Privacidade', en: 'Privacy Policy' },
  'landing.security': { pt: 'Segurança da Informação', en: 'Information Security' },
  'landing.rights': { pt: '© 2026 Licenfy Tecnologia S.A. Todos os direitos reservados.', en: '© 2026 Licenfy Tecnologia S.A. All rights reserved.' },
  'landing.modalTitle': { pt: 'Agende uma Demonstração Personalizada', en: 'Schedule a Personalized Demo' },
  'landing.modalIntro': { pt: 'Veja como o Licenfy elimina o risco de multas e interdições nas suas filiais com inteligência artificial e OCR.', en: 'See how Licenfy eliminates fines and shutdown risks across your branches with AI and OCR.' },
  'landing.modalName': { pt: 'Seu Nome Completo', en: 'Your Full Name' },
  'landing.modalEmail': { pt: 'E-mail Corporativo', en: 'Work Email' },
  'landing.modalPhone': { pt: 'Telefone Corporativo', en: 'Corporate Phone' },
  'landing.modalUnits': { pt: 'Quantidade de Filiais / Unidades', en: 'Number of Branches / Units' },
  'landing.modalSubmit': { pt: 'Agendar com Especialista', en: 'Schedule with a Specialist' },
  'landing.modalSandbox': { pt: 'Entrar no Sistema Direto (Sandbox)', en: 'Enter Direct System (Sandbox)' },

  // Dashboard
  'dashboard.desc': { pt: 'Monitoramento preventivo de alvarás, licenças ambientais, vistorias e garantias de ativos.', en: 'Preventive monitoring of permits, environmental licenses, inspections and asset warranties.' },
  'dashboard.alertAria': { pt: '1 alerta de manutenção vinculado', en: '1 linked maintenance alert' },
  'dashboard.alertTitle': { pt: 'Manutenção vinculada', en: 'Linked maintenance' },
  'dashboard.alertText': { pt: 'AVCB vence em 25 dias', en: 'Fire safety certificate expires in 25 days' },
  'dashboard.alertDesc': { pt: 'A renovação depende da recarga e vistoria da Bateria de Extintores (EQ-0199).', en: 'Renewal depends on recharging and inspecting the fire extinguisher battery (EQ-0199).' },
  'dashboard.viewAsset': { pt: 'Ver ativo vinculado', en: 'View linked asset' },
  'dashboard.upload': { pt: 'Upload de Licença', en: 'Upload License' },
  'dashboard.dossier': { pt: 'Dossiê Fiscalização', en: 'Inspection Dossier' },
  'dashboard.filterUnit': { pt: 'Filtrar Unidade:', en: 'Filter Unit:' },
  'dashboard.allUnits': { pt: 'Todas as Unidades (Visão Consolidada)', en: 'All Units (Consolidated View)' },
  'dashboard.scoreCaption': { pt: 'Índice Geral de Regularidade', en: 'Overall Compliance Index' },
  'dashboard.scoreTitle': { pt: 'Score de Compliance', en: 'Compliance Score' },
  'dashboard.compliance': { pt: 'Conformidade', en: 'Compliance' },
  'dashboard.validLicenses': { pt: 'Licenças Válidas', en: 'Valid Licenses' },
  'dashboard.renewSoon': { pt: 'Renovação Próxima (< 30d)', en: 'Renewal Soon (< 30d)' },
  'dashboard.criticalRisk': { pt: 'Risco Crítico / Iminente', en: 'Critical / Imminent Risk' },
  'dashboard.zeroFines': { pt: 'Zero multas nos últimos 12 meses nas filiais monitoradas.', en: 'Zero fines in the last 12 months at monitored branches.' },
  'dashboard.regularDocs': { pt: 'Documentos & Licenças em dia', en: 'Documents & Licenses Up to Date' },
  'dashboard.regularDocsDesc': { pt: 'Sem pendências jurídicas ou de órgãos fiscalizadores.', en: 'No pending legal or regulatory issues.' },
  'dashboard.attentionDocs': { pt: 'Prazos em contagem regressiva', en: 'Deadlines approaching' },
  'dashboard.attentionDocsDesc': { pt: 'Disparos de alertas em andamento (30 a 60 dias).', en: 'Alerts in progress (30 to 60 days).' },
  'dashboard.urgentDocs': { pt: 'Risco iminente ou pendência crítica', en: 'Imminent risk or critical pending issue' },
  'dashboard.urgentDocsDesc': { pt: 'Ação emergencial recomendada para evitar auto de infração.', en: 'Immediate action recommended to avoid an infringement notice.' },
  'dashboard.monitoringTitle': { pt: 'Monitoramento Ativo de Obrigações', en: 'Active Obligation Monitoring' },
  'dashboard.monitoringSub': { pt: 'Alvarás, licenças ambientais, sanitárias e vistorias sob gestão contínua', en: 'Permits, environmental and sanitary licenses and inspections under continuous management' },
  'dashboard.accessVault': { pt: 'Acessar Cofre Digital', en: 'Access Digital Vault' },
  'dashboard.status': { pt: 'Status', en: 'Status' },
  'dashboard.document': { pt: 'Documento / Obrigação', en: 'Document / Obligation' },
  'dashboard.issuer': { pt: 'Órgão Emissor', en: 'Issuing Body' },
  'dashboard.unitBranch': { pt: 'Unidade / Filial', en: 'Unit / Branch' },
  'dashboard.expiration': { pt: 'Vencimento', en: 'Expiration' },
  'dashboard.linkedAsset': { pt: 'Ativo Vinculado', en: 'Linked Asset' },
  'dashboard.preventiveAction': { pt: 'Ação Preventiva', en: 'Preventive Action' },
  'dashboard.daysRemaining': { pt: 'dias restantes', en: 'days remaining' },
  'dashboard.noLink': { pt: 'Sem vínculo direto', en: 'No direct link' },
  'dashboard.emailSent': { pt: 'E-mail Disparado!', en: 'Email Sent!' },
  'dashboard.alertEmail': { pt: 'Alertar por E-mail', en: 'Alert by Email' },
  'status.regular': { pt: 'Regular', en: 'Compliant' },
  'status.attention': { pt: 'Atenção', en: 'Attention' },
  'status.urgent': { pt: 'Urgente', en: 'Urgent' },
  'status.valid': { pt: 'Válido', en: 'Valid' },
  'status.renew': { pt: 'Renovar em Breve', en: 'Renew Soon' },
  'status.expiring': { pt: 'Vencendo', en: 'Expiring' },
  'status.current': { pt: 'Vigente', en: 'Current' },
  'status.renewing': { pt: 'Em Renovação', en: 'Renewing' },
  'status.delivered': { pt: 'Entregue', en: 'Delivered' },
  'status.critical': { pt: 'Crítica', en: 'Critical' },
  'status.read': { pt: 'Lido', en: 'Read' },
  'status.actionTaken': { pt: 'Ação Tomada', en: 'Action Taken' },
  'status.currentShort': { pt: 'Atual', en: 'Current' },

  // Unidades
  'units.structure': { pt: 'Estrutura da operação', en: 'Operation structure' },
  'units.desc': { pt: 'Organize a rede em empresa → unidade → documentos e ativos, sem concentrar o conhecimento em uma única pessoa.', en: 'Organize the network as company → unit → documents and assets, without concentrating knowledge in one person.' },
  'units.new': { pt: 'Nova unidade', en: 'New unit' },
  'units.active': { pt: 'unidades ativas', en: 'active units' },
  'units.docsAssets': { pt: 'documentos e ativos por unidade', en: 'documents and assets per unit' },
  'units.network': { pt: 'Rede de unidades', en: 'Unit network' },
  'units.registered': { pt: 'cadastradas', en: 'registered' },
  'units.selected': { pt: 'UNIDADE SELECIONADA', en: 'SELECTED UNIT' },
  'units.address': { pt: 'Endereço', en: 'Address' },
  'units.documents': { pt: 'Documentos', en: 'Documents' },
  'units.managedDocs': { pt: 'documentos sob gestão', en: 'documents under management' },
  'units.assets': { pt: 'Ativos', en: 'Assets' },
  'units.linkedAssets': { pt: 'ativos vinculados', en: 'linked assets' },
  'units.responsible': { pt: 'Responsáveis e destinatários', en: 'Owners and recipients' },
  'units.responsibleDesc': { pt: 'Todos recebem alertas automáticos conforme a unidade.', en: 'Everyone receives automatic alerts for their unit.' },
  'units.addResponsible': { pt: 'Adicionar responsável', en: 'Add owner' },
  'units.primary': { pt: 'Principal', en: 'Primary' },
  'units.formKicker': { pt: 'CADASTRO DE FILIAL', en: 'BRANCH REGISTRATION' },
  'units.formTitle': { pt: 'Nova unidade', en: 'New unit' },
  'units.name': { pt: 'Nome da unidade', en: 'Unit name' },
  'units.city': { pt: 'Cidade', en: 'City' },
  'units.state': { pt: 'UF', en: 'State' },
  'units.manager': { pt: 'Gestor responsável', en: 'Responsible manager' },
  'units.managerEmail': { pt: 'E-mail do gestor', en: 'Manager email' },
  'units.phone': { pt: 'Telefone corporativo', en: 'Corporate phone' },
  'common.cancel': { pt: 'Cancelar', en: 'Cancel' },
  'common.saveUnit': { pt: 'Salvar unidade', en: 'Save unit' },
  'common.close': { pt: 'Fechar', en: 'Close' },
  'common.add': { pt: 'Adicionar', en: 'Add' },
  'common.days': { pt: 'dias', en: 'days' },
  'common.view': { pt: 'Visualizar', en: 'View' },
  'common.pdf': { pt: 'Ver PDF', en: 'View PDF' },

  // Digital vault
  'vault.kicker': { pt: 'Cofre Digital Criptografado & Leitura Automática', en: 'Encrypted Digital Vault & Automatic Reading' },
  'vault.desc': { pt: 'Centralize todos os PDFs, notas fiscais e alvarás. O sistema lê as informações e preenche as datas automaticamente.', en: 'Centralize all PDFs, invoices and permits. The system reads information and fills dates automatically.' },
  'vault.ocrTitle': { pt: 'Área de Upload & Digitalização OCR', en: 'Upload & OCR Scanning Area' },
  'vault.ocrDesc': { pt: 'Arraste documentos PDF ou escolha um exemplo oficial para simular a extração automática de dados.', en: 'Drag PDF documents or choose an official sample to simulate automatic data extraction.' },
  'vault.secureRead': { pt: 'Leitura de documentos segura', en: 'Secure document reading' },
  'vault.secureReadDesc': { pt: 'os dados são extraídos e conferidos no cofre da empresa.', en: 'data is extracted and checked in the company vault.' },
  'vault.dropTitle': { pt: 'Arraste seu PDF ou imagem aqui', en: 'Drag your PDF or image here' },
  'vault.dropDesc': { pt: 'Suporta PDF, JPG e PNG (até 4 MB)', en: 'Supports PDF, JPG and PNG (up to 4 MB)' },
  'vault.selectFile': { pt: 'Selecionar Arquivo do Computador', en: 'Select File from Computer' },
  'vault.processing': { pt: 'Processando Documento...', en: 'Processing Document...' },
  'vault.success': { pt: 'Leitura do Documento Concluída com Sucesso!', en: 'Document Reading Completed Successfully!' },
  'vault.successDesc': { pt: 'Revise os campos preenchidos automaticamente abaixo antes de arquivar no cofre.', en: 'Review the automatically filled fields below before archiving in the vault.' },
  'vault.sample': { pt: 'Usar exemplo simulado', en: 'Use simulated sample' },
  'vault.extracted': { pt: 'Confirmação dos dados extraídos', en: 'Confirm extracted data' },
  'vault.review': { pt: 'Revisão de dados.', en: 'Data review.' },
  'vault.reviewDesc': { pt: 'Confira órgão emissor, datas, valor e unidade antes de salvar no sistema.', en: 'Check issuing body, dates, value and unit before saving.' },
  'vault.obligation': { pt: 'Título da Obrigação / Licença', en: 'Obligation / License Title' },
  'vault.issuer': { pt: 'Órgão Emissor', en: 'Issuing Body' },
  'vault.category': { pt: 'Categoria Jurídica', en: 'Legal Category' },
  'vault.protocol': { pt: 'Número do Registro / Protocolo', en: 'Registration / Protocol Number' },
  'vault.unit': { pt: 'Unidade / Filial Pertencente', en: 'Owning Unit / Branch' },
  'vault.issueDate': { pt: 'Data de emissão', en: 'Issue date' },
  'vault.expiryDate': { pt: 'Data de Vencimento Oficial', en: 'Official Expiration Date' },
  'vault.fineEstimate': { pt: 'Estimativa de Multa se Não Renovado (R$)', en: 'Estimated Fine if Not Renewed (R$)' },
  'vault.linkedAsset': { pt: 'Ativo Físico Vinculado (Opcional)', en: 'Linked Physical Asset (Optional)' },
  'vault.validationNotes': { pt: 'Notas de Validação OCR', en: 'OCR Validation Notes' },
  'vault.confirmArchive': { pt: 'Confirmar dados e arquivar', en: 'Confirm data and archive' },
  'vault.documents': { pt: 'Documentos e Licenças no Cofre Digital', en: 'Documents and Licenses in Digital Vault' },
  'vault.indexed': { pt: 'documentos indexados e protegidos', en: 'indexed and protected documents' },
  'vault.searchPlaceholder': { pt: 'Buscar por licença, órgão ou número...', en: 'Search by license, body or number...' },
  'vault.allCategories': { pt: 'Todas as Categorias', en: 'All Categories' },
  'vault.viewDoc': { pt: 'Visualizar Documento', en: 'View Document' },
  'vault.versions': { pt: 'Versões', en: 'Versions' },
  'vault.historyKicker': { pt: 'HISTÓRICO IMUTÁVEL', en: 'IMMUTABLE HISTORY' },
  'vault.historyDesc': { pt: 'Renovações anteriores ficam preservadas e nunca substituem a versão arquivada.', en: 'Previous renewals are preserved and never replace the archived version.' },
  'vault.currentVersion': { pt: 'Versão atual', en: 'Current version' },
  'vault.previousVersion': { pt: 'Versão anterior', en: 'Previous version' },
  'vault.archived': { pt: 'Arquivada', en: 'Archived' },
  'vault.confirmedVault': { pt: 'confirmado no cofre', en: 'confirmed in the vault' },
  'vault.auditPreserved': { pt: 'Arquivo preservado para auditoria e rastreabilidade', en: 'File preserved for audit and traceability' },

  // Assets
  'assets.kicker': { pt: 'Operação na Ponta sem Necessidade de App', en: 'Point-of-Use Operation Without an App' },
  'assets.desc': { pt: 'Etiquetas físicas aplicadas nos equipamentos. Ao escanear pelo celular, qualquer colaborador acessa garantias, manutenções e NFs.', en: 'Physical labels applied to equipment. By scanning with a phone, any collaborator can access warranties, maintenance and invoices.' },
  'assets.register': { pt: 'Cadastrar ativo', en: 'Register asset' },
  'assets.modalTitle': { pt: 'Novo ativo e etiqueta QR', en: 'New asset and QR label' },
  'assets.modalDesc': { pt: 'Cadastre o equipamento e vincule a nota fiscal para acompanhar garantia e manutenção.', en: 'Register the equipment and link the invoice to track warranty and maintenance.' },
  'assets.equipmentName': { pt: 'Nome do equipamento', en: 'Equipment name' },
  'assets.assetTag': { pt: 'Etiqueta patrimonial', en: 'Asset tag' },
  'assets.unit': { pt: 'Unidade', en: 'Unit' },
  'assets.invoice': { pt: 'Nota fiscal', en: 'Invoice' },
  'assets.warrantyUntil': { pt: 'Garantia até', en: 'Warranty until' },
  'assets.saveQr': { pt: 'Salvar e gerar QR', en: 'Save and generate QR' },
  'assets.all': { pt: 'Todos os Ativos', en: 'All Assets' },
  'assets.extinguishers': { pt: 'Extintores & AVCB', en: 'Extinguishers & AVCB' },
  'assets.generators': { pt: 'Geradores', en: 'Generators' },
  'assets.hvac': { pt: 'Climatização & Chillers', en: 'HVAC & Chillers' },
  'assets.upToDate': { pt: 'Em Dia', en: 'Up to Date' },
  'assets.reviewSoon': { pt: 'Revisão Próxima', en: 'Review Soon' },
  'assets.urgent': { pt: 'Urgente', en: 'Urgent' },
  'assets.location': { pt: 'Localização:', en: 'Location:' },
  'assets.warranty': { pt: 'Garantia do Fabricante:', en: 'Manufacturer Warranty:' },
  'assets.unification': { pt: 'Unificação Legal + Operacional', en: 'Legal + Operational Unification' },
  'assets.lastIntervention': { pt: 'Última Intervenção:', en: 'Last Intervention:' },
  'assets.maintenanceCount': { pt: 'manutenções registradas', en: 'recorded maintenance activities' },
  'assets.qrLabel': { pt: 'Etiqueta QR Code', en: 'QR Code Label' },
  'assets.operatorView': { pt: 'Visão do Operador', en: 'Operator View' },
  'assets.physicalTitle': { pt: 'Etiqueta Física com QR Code Patrimonial', en: 'Physical Label with Asset QR Code' },
  'assets.physicalDesc': { pt: 'Etiqueta pronta para aplicação direta no equipamento. O QR Code permite consulta instantânea pelo navegador do celular sem instalar aplicativos.', en: 'Label ready for direct application to equipment. The QR Code enables instant lookup from a phone browser without installing apps.' },
  'assets.scanCamera': { pt: 'Aponte a câmera', en: 'Point the camera' },
  'assets.assetProperty': { pt: 'PATRIMÔNIO', en: 'ASSET' },
  'assets.warrantyLabel': { pt: 'Garantia até:', en: 'Warranty until:' },
  'assets.operationalManagement': { pt: 'GESTÃO OPERACIONAL LICENFY', en: 'LICENFY OPERATIONAL MANAGEMENT' },
  'assets.downloadQr': { pt: 'Baixar QR como PNG', en: 'Download QR as PNG' },
  'assets.printLabel': { pt: 'Imprimir Etiqueta Adesiva', en: 'Print Adhesive Label' },
  'assets.simulatorTitle': { pt: 'Simulador: Visão do Operador no Local', en: 'Simulator: Operator View On Site' },
  'assets.connected': { pt: 'Conectado', en: 'Connected' },
  'assets.warrantyActive': { pt: 'Garantia Vigente', en: 'Active Warranty' },
  'assets.validUntil': { pt: 'Válida até', en: 'Valid until' },
  'assets.remainingDays': { pt: 'dias restantes', en: 'days remaining' },
  'assets.purchaseInvoice': { pt: 'NF de Compra:', en: 'Purchase Invoice:' },
  'assets.interventionHistory': { pt: 'Histórico de Intervenções', en: 'Intervention History' },
  'assets.technician': { pt: 'Técnico:', en: 'Technician:' },
  'assets.reportIssue': { pt: 'Reportar Ocorrência / Acionar Garantia', en: 'Report Issue / Activate Warranty' },
  'assets.issueRegistered': { pt: 'Chamado Registrado com Sucesso!', en: 'Request Registered Successfully!' },
  'assets.howWorks': { pt: 'Como funciona na prática?', en: 'How does it work in practice?' },
  'assets.howWorksDesc': { pt: 'O técnico aponta a câmera nativa do smartphone para a etiqueta física colada na máquina.', en: 'The technician points the smartphone camera at the physical label attached to the machine.' },
  'assets.directAccess': { pt: 'Acesso direto:', en: 'Direct access:' },
  'assets.directAccessDesc': { pt: 'Não exige download de aplicativo em lojas.', en: 'No app store download required.' },
  'assets.savesCosts': { pt: 'Evita despesas:', en: 'Saves costs:' },
  'assets.savesCostsDesc': { pt: 'Consulta na hora se a peça ainda está coberta pela garantia da nota fiscal.', en: 'Check instantly whether the part is still covered by the invoice warranty.' },
  'assets.traceability': { pt: 'Rastreabilidade:', en: 'Traceability:' },
  'assets.traceabilityDesc': { pt: 'Histórico das revisões preventivas atualizado em tempo real.', en: 'Preventive maintenance history updated in real time.' },

  // Notifications
  'notif.kicker': { pt: 'Comunicação Corporativa & Trilha de Auditoria', en: 'Corporate Communication & Audit Trail' },
  'notif.rulesTitle': { pt: 'Alertas de Disparo Corporativo', en: 'Corporate Trigger Alerts' },
  'notif.rulesSub': { pt: 'Gatilhos automáticos configurados antes de qualquer vencimento', en: 'Automatic triggers configured before any expiration' },
  'notif.daysBefore': { pt: 'dias antes', en: 'days before' },
  'notif.infoLevel': { pt: 'Informativo', en: 'Informational' },
  'notif.preventiveLevel': { pt: 'Alerta Preventivo', en: 'Preventive Alert' },
  'notif.criticalLevel': { pt: 'Crítico / Ação Imediata', en: 'Critical / Immediate Action' },
  'notif.customTitle': { pt: 'Adicionar Alerta Customizado', en: 'Add Custom Alert' },
  'notif.customDesc': { pt: 'Defina prazos e destinatários específicos para sua empresa.', en: 'Set specific deadlines and recipients for your company.' },
  'notif.recipientsPlaceholder': { pt: 'E-mails corporativos separados por vírgula', en: 'Corporate emails separated by commas' },
  'notif.simulateTitle': { pt: 'Simular Envio Imediato de E-mail de Alerta', en: 'Simulate Immediate Alert Email' },
  'notif.sending': { pt: 'Disparando...', en: 'Sending...' },
  'notif.sendTest': { pt: 'Disparar Teste', en: 'Send Test' },
  'notif.success': { pt: 'E-mail corporativo disparado e registrado no histórico de auditoria!', en: 'Corporate email sent and recorded in the audit history!' },
  'notif.logsTitle': { pt: 'Histórico de Disparos de E-mail (Auditoria Corporativa)', en: 'Email Dispatch History (Corporate Audit)' },
  'notif.logsSub': { pt: 'Trilha de auditoria legal com registro de data, hora, destinatário e status de entrega de cada alerta', en: 'Legal audit trail recording date, time, recipient and delivery status of each alert' },
  'notif.channel': { pt: 'Canal', en: 'Channel' },
  'notif.dateTime': { pt: 'Data / Hora', en: 'Date / Time' },
  'notif.recipient': { pt: 'Destinatário', en: 'Recipient' },
  'notif.documentAsset': { pt: 'Documento / Ativo', en: 'Document / Asset' },
  'notif.advance': { pt: 'Antecedência', en: 'Advance notice' },
  'notif.deliveryStatus': { pt: 'Status de Entrega', en: 'Delivery Status' },
  'notif.preview': { pt: 'Prévia do E-mail', en: 'Email preview' },

  // Inspection
  'inspection.kicker': { pt: 'Modo Fiscalização Imediata', en: 'Immediate Inspection Mode' },
  'inspection.desc': { pt: 'Compilação instantânea de todos os alvarás, laudos e licenças vigentes, pronta para auditoria externa e fiscais.', en: 'Instant compilation of all current permits, reports and licenses, ready for external audits and inspectors.' },
  'inspection.unit': { pt: 'Unidade a Fiscalizar:', en: 'Unit to Inspect:' },
  'inspection.print': { pt: 'Imprimir / Exportar PDF do Dossiê', en: 'Print / Export Dossier PDF' },
  'inspection.included': { pt: 'Documentos incluídos', en: 'Included documents' },
  'inspection.includedDesc': { pt: 'Selecione o que será consolidado no PDF.', en: 'Select what will be consolidated in the PDF.' },
  'inspection.platformCaption': { pt: 'PLATAFORMA INTEGRADA DE COMPLIANCE E REGULARIDADE OPERACIONAL', en: 'INTEGRATED COMPLIANCE AND OPERATIONAL REGULARITY PLATFORM' },
  'inspection.certificate': { pt: 'CERTIFICADO DIGITAL DE CONFORMIDADE', en: 'DIGITAL CERTIFICATE OF COMPLIANCE' },
  'inspection.issued': { pt: 'Emissão:', en: 'Issued:' },
  'inspection.authentication': { pt: 'Autenticação:', en: 'Authentication:' },
  'inspection.generalStatus': { pt: 'Status Geral:', en: 'General Status:' },
  'inspection.audited': { pt: 'REGULAR E AUDITADO', en: 'COMPLIANT AND AUDITED' },
  'inspection.company': { pt: 'Razão Social / Filial', en: 'Company / Branch' },
  'inspection.cnpj': { pt: 'CNPJ Oficial', en: 'Official CNPJ' },
  'inspection.cityState': { pt: 'Município / UF', en: 'City / State' },
  'inspection.legalOwner': { pt: 'Responsável Legal / Jurídico', en: 'Legal / Compliance Owner' },
  'inspection.score': { pt: 'Score de Regularidade', en: 'Compliance Score' },
  'inspection.validLicenses': { pt: 'Licenças Válidas Anexadas', en: 'Attached Valid Licenses' },
  'inspection.inspectedAssets': { pt: 'Ativos Físicos Inspecionados', en: 'Inspected Physical Assets' },
  'inspection.pendingViolations': { pt: 'Autuações Pendentes', en: 'Pending Violations' },
  'inspection.section1': { pt: '1. Relação Oficial de Alvarás, Licenças e Laudos Técnicos', en: '1. Official List of Permits, Licenses and Technical Reports' },
  'inspection.document': { pt: 'Documento / Obrigação', en: 'Document / Obligation' },
  'inspection.issuingBody': { pt: 'Órgão Expedidor', en: 'Issuing Authority' },
  'inspection.registration': { pt: 'Nº Registro / Protocolo', en: 'Registration / Protocol No.' },
  'inspection.issueDate': { pt: 'Data de Emissão', en: 'Issue Date' },
  'inspection.officialValidity': { pt: 'Validade Oficial', en: 'Official Validity' },
  'inspection.legalStatus': { pt: 'Status Legal', en: 'Legal Status' },
  'inspection.section2': { pt: '2. Certificação de Manutenção Preventiva dos Ativos de Segurança', en: '2. Preventive Maintenance Certification for Safety Assets' },
  'inspection.maintenanceDesc': { pt: 'Todos os equipamentos críticos vinculados às licenças municipais e estaduais possuem plano de manutenção preventiva contínuo e etiquetas patrimoniais com QR Code registradas na plataforma:', en: 'All critical equipment linked to municipal and state licenses has a continuous preventive maintenance plan and QR Code asset labels registered on the platform:' },
  'inspection.fireTitle': { pt: 'Sistemas de Prevenção e Combate a Incêndio', en: 'Fire Prevention and Fighting Systems' },
  'inspection.fireExtinguishers': { pt: 'Recarga de Extintores:', en: 'Extinguisher recharge:' },
  'inspection.fireExtinguishersDesc': { pt: 'Teste hidrostático e anéis de identificação atualizados.', en: 'Updated hydrostatic test and identification rings.' },
  'inspection.hydrants': { pt: 'Pressurização dos Hidrantes:', en: 'Hydrant pressurization:' },
  'inspection.hydrantsDesc': { pt: 'Válvulas e mangueiras com laudo de teste estanque.', en: 'Valves and hoses with a watertight test report.' },
  'inspection.electricalTitle': { pt: 'Instalações Elétricas & SPDA (Para-raios)', en: 'Electrical Installations & Lightning Protection' },
  'inspection.nr10': { pt: 'Laudo NR-10:', en: 'NR-10 report:' },
  'inspection.nr10Desc': { pt: 'Termografia de painéis e aterramento conformes à norma regulamentadora.', en: 'Panel thermography and grounding compliant with regulations.' },
  'inspection.generators': { pt: 'Geradores de Emergência:', en: 'Emergency generators:' },
  'inspection.generatorsDesc': { pt: 'Bateria de testes de partida quinzenais registrada.', en: 'Recorded biweekly start-test battery.' },
  'inspection.complianceManager': { pt: 'Gestor Responsável de Compliance & Operações', en: 'Compliance & Operations Manager' },
  'inspection.digitalSignature': { pt: 'Assinatura Digital ICP-Brasil Padrão PAdES', en: 'Standard ICP-Brasil PAdES Digital Signature' },
  'inspection.issuedSecure': { pt: 'Dossiê emitido em ambiente seguro pela plataforma Licenfy. Código de validação pública:', en: 'Dossier issued in a secure environment by Licenfy. Public validation code:' },
  'inspection.validAuditors': { pt: 'Documento válido para exibição a auditores e autoridades públicas fiscalizadoras.', en: 'Document valid for presentation to auditors and public inspection authorities.' },
  'inspection.historyTitle': { pt: 'Histórico de dossiês gerados', en: 'Generated dossier history' },
  'inspection.historyDesc': { pt: 'Rastreabilidade de todas as exportações por unidade.', en: 'Traceability of all exports by unit.' },
  'inspection.documentsCount': { pt: 'documentos', en: 'documents' },

  // ROI
  'roi.kicker': { pt: 'Retorno Financeiro Mensurável', en: 'Measurable Financial Return' },
  'roi.desc': { pt: 'Painel executivo que contabiliza a economia gerada ao acionar garantias dentro do prazo e evitar multas regulatórias e paralisações.', en: 'Executive dashboard accounting for savings from warranties used on time and avoided regulatory fines and shutdowns.' },
  'roi.totalLabel': { pt: 'ECONOMIA TOTAL ACUMULADA PELA PLATAFORMA', en: 'TOTAL SAVINGS ACCUMULATED BY THE PLATFORM' },
  'roi.totalDesc': { pt: 'Ganhos auditados combinando multas regulatórias eliminadas, peças em garantia acionadas e horas operacionais reduzidas nas filiais.', en: 'Audited gains from avoided regulatory fines, warranty parts and reduced branch operating hours.' },
  'roi.multiplier': { pt: 'Multiplicador de ROI', en: 'ROI Multiplier' },
  'roi.netReturn': { pt: 'Retorno Líquido', en: 'Net Return' },
  'roi.hoursSaved': { pt: 'Horas Poupadas', en: 'Hours Saved' },
  'roi.legalPrevention': { pt: 'Prevenção Legal', en: 'Legal Prevention' },
  'roi.finesAvoided': { pt: 'Multas Regulatórias Evitadas', en: 'Regulatory Fines Avoided' },
  'roi.finesDesc': { pt: 'Valor calculado com base nas tabelas de infração dos órgãos (Prefeituras, Bombeiros, ANVISA e Órgãos Ambientais).', en: 'Value calculated from municipal, fire, ANVISA and environmental authority penalty tables.' },
  'roi.assetManagement': { pt: 'Gestão de Ativos', en: 'Asset Management' },
  'roi.warrantyParts': { pt: 'Peças e Reparos em Garantia', en: 'Warranty Parts and Repairs' },
  'roi.warrantyDesc': { pt: 'Serviços e trocas de componentes realizadas sem custo ao consultar a nota fiscal e vigência via QR Code.', en: 'Services and component replacements completed at no cost by checking the invoice and warranty via QR Code.' },
  'roi.efficiency': { pt: 'Eficiência B2B', en: 'B2B Efficiency' },
  'roi.teamTime': { pt: 'Tempo de Equipe Otimizado', en: 'Optimized Team Time' },
  'roi.teamTimeDesc': { pt: 'Eliminação de planilhas manuais e digitação burocrática pelo uso do OCR e alertas automáticos.', en: 'Elimination of manual spreadsheets and bureaucratic data entry through OCR and automatic alerts.' },
  'roi.preventedTitle': { pt: 'Autuações e Multas Prevenidas', en: 'Prevented Violations and Fines' },
  'roi.preventedDesc': { pt: 'Obrigações renovadas dentro do prazo antes da autuação', en: 'Obligations renewed on time before a violation' },
  'roi.obligation': { pt: 'Obrigação / Licença', en: 'Obligation / License' },
  'roi.body': { pt: 'Órgão', en: 'Authority' },
  'roi.branch': { pt: 'Filial', en: 'Branch' },
  'roi.fineAvoided': { pt: 'Multa Evitada', en: 'Fine Avoided' },
  'roi.warrantyTitle': { pt: 'Garantias de Ativos Acionadas a Tempo', en: 'Asset Warranties Activated on Time' },
  'roi.warrantySavingsDesc': { pt: 'Economia em manutenções cobertas pelo fabricante', en: 'Savings on manufacturer-covered maintenance' },
  'roi.equipment': { pt: 'Equipamento', en: 'Equipment' },
  'roi.partService': { pt: 'Componente / Serviço', en: 'Part / Service' },
  'roi.date': { pt: 'Data', en: 'Date' },
  'roi.savings': { pt: 'Economia Gerada', en: 'Savings Generated' },

  // Public asset page
  'assetPage.identified': { pt: 'ATIVO IDENTIFICADO', en: 'ASSET IDENTIFIED' },
  'assetPage.notFound': { pt: 'ATIVO NÃO ENCONTRADO', en: 'ASSET NOT FOUND' },
  'assetPage.property': { pt: 'Patrimônio:', en: 'Asset tag:' },
  'assetPage.unit': { pt: 'Unidade', en: 'Unit' },
  'assetPage.location': { pt: 'Localização', en: 'Location' },
  'assetPage.nextMaintenance': { pt: 'Próxima manutenção', en: 'Next maintenance' },
  'assetPage.notFoundText': { pt: 'Este QR Code não corresponde a um ativo disponível.', en: 'This QR Code does not correspond to an available asset.' },
  'assetPage.notFoundDesc': { pt: 'Confira a etiqueta ou entre em contato com a equipe responsável.', en: 'Check the label or contact the responsible team.' },
  'assetPage.go': { pt: 'Ir para Licenfy', en: 'Go to Licenfy' },

  // Auth — painel de marca e placeholders
  'auth.brandKicker': { pt: 'PLATAFORMA DE COMPLIANCE', en: 'COMPLIANCE PLATFORM' },
  'auth.brandTitle': { pt: 'Controle total, sem perder o ritmo do dia a dia.', en: 'Complete control without slowing down your day.' },
  'auth.brandDesc': { pt: 'Documentos, prazos, ativos e responsáveis em um só lugar.', en: 'Documents, deadlines, assets and owners in one place.' },
  'auth.brandPoint1': { pt: 'Acesso seguro para sua equipe', en: 'Secure access for your team' },
  'auth.brandPoint2': { pt: 'Alertas e histórico auditável', en: 'Alerts and auditable history' },
  'auth.brandPoint3': { pt: 'Visão consolidada por unidade', en: 'Consolidated view by unit' },
  'auth.brandPoint4': { pt: 'Ambiente de teste com dados de exemplo', en: 'Test environment with sample data' },
  'auth.emailPlaceholder': { pt: 'seu@empresa.com.br', en: 'you@company.com' },
  'auth.passwordPlaceholder': { pt: 'Sua senha', en: 'Your password' },
  'auth.namePlaceholder': { pt: 'Ex: Carlos Eduardo', en: 'E.g.: Alex Johnson' },
  'auth.minPassword': { pt: 'Mínimo 3 caracteres', en: 'Minimum 3 characters' },
  'auth.repeatPassword': { pt: 'Repita a senha criada', en: 'Repeat the password' },

  // Landing — navegação, planos e rodapé
  'landing.mainNavAria': { pt: 'Navegação principal', en: 'Main navigation' },
  'landing.heroVisualAria': { pt: 'Painel de operação Licenfy em computador e celular', en: 'Licenfy operations dashboard on desktop and mobile' },
  'landing.carouselAria': { pt: 'Escolher demonstração do produto', en: 'Choose product demonstration' },
  'landing.viewSlide': { pt: 'Ver', en: 'View' },
  'landing.monthlyPeriod': { pt: '/mês', en: '/month' },
  'landing.annualPeriod': { pt: '/ano', en: '/year' },
  'landing.annualNoteStrong': { pt: 'R$ 100/mês', en: 'R$ 100/month' },
  'landing.footerPlatform': { pt: 'Plataforma', en: 'Platform' },
  'landing.footerSolutions': { pt: 'Soluções', en: 'Solutions' },
  'landing.footerRisk': { pt: 'Inteligência de Risco', en: 'Risk Intelligence' },
  'landing.footerEnterprise': { pt: 'Para Operações Enterprise', en: 'For Enterprise Operations' },
  'landing.footerLicenseAutomation': { pt: 'Automação de Licenças', en: 'License Automation' },
  'landing.footerAssetManagement': { pt: 'Gestão de Ativos', en: 'Asset Management' },
  'landing.modalUnits1': { pt: '1 a 5 filiais', en: '1 to 5 branches' },
  'landing.modalUnits2': { pt: '6 a 20 filiais', en: '6 to 20 branches' },
  'landing.modalUnits3': { pt: '21 a 50 filiais', en: '21 to 50 branches' },
  'landing.modalUnits4': { pt: 'Mais de 50 filiais', en: 'More than 50 branches' },

  // Cofre — opções e estados
  'vault.categoryPermit': { pt: 'Alvará de Funcionamento', en: 'Operating Permit' },
  'vault.categoryFire': { pt: 'Corpo de Bombeiros / AVCB', en: 'Fire Department / AVCB' },
  'vault.categoryHealth': { pt: 'Vigilância Sanitária', en: 'Health Inspection' },
  'vault.categoryEnvironmental': { pt: 'Licenciamento Ambiental', en: 'Environmental Licensing' },
  'vault.categorySafety': { pt: 'Segurança do Trabalho / NR', en: 'Occupational Safety / NR' },
  'vault.categoryPermits': { pt: 'Alvarás', en: 'Permits' },
  'vault.categoryFireShort': { pt: 'Bombeiros / AVCB', en: 'Fire / AVCB' },
  'vault.categoryHealthShort': { pt: 'Sanitária', en: 'Health' },
  'vault.categoryEnvironmentalShort': { pt: 'Ambiental', en: 'Environmental' },
  'vault.categorySafetyShort': { pt: 'Segurança do Trabalho', en: 'Occupational Safety' },
  'vault.expiry': { pt: 'Vencimento', en: 'Expiration' },
  'vault.days': { pt: 'dias', en: 'days' },
  'vault.fileSize': { pt: '1.5 MB', en: '1.5 MB' },
  'vault.closeHistory': { pt: 'Fechar histórico', en: 'Close history' },

  // Assets — formulários e etiquetas
  'assets.equipmentPlaceholder': { pt: 'Ex.: Bomba de incêndio', en: 'E.g.: Fire pump' },
  'assets.invoicePlaceholder': { pt: 'NF-e 000.000 / Série 1', en: 'Invoice 000.000 / Series 1' },
  'assets.assetsCount': { pt: 'ativos', en: 'assets' },

  // Notificações — estados dos registros
  'notif.statusRead': { pt: 'Lido', en: 'Read' },
  'notif.statusAction': { pt: 'Ação Tomada', en: 'Action Taken' },
  'notif.statusDelivered': { pt: 'Entregue', en: 'Delivered' },

  // Utilitários de layout
  'common.branch': { pt: 'Filial', en: 'Branch' },
  'common.document': { pt: 'Documento', en: 'Document' },
  'common.asset': { pt: 'Ativo', en: 'Asset' },
  'common.required': { pt: 'Obrigatório', en: 'Required' },
  'common.brand': { pt: 'Licenfy Tecnologia', en: 'Licenfy Technology' },
  'common.seePlans': { pt: 'Conheça nossos planos e assine', en: 'View our plans and subscribe' },
  'common.notifications': { pt: 'Notificações Recentes', en: 'Recent Notifications' },
  'common.openMenu': { pt: 'Abrir ou fechar menu de módulos', en: 'Open or close system modules menu' },
  'common.openMobileMenu': { pt: 'Abrir menu de módulos', en: 'Open system modules menu' },
  'common.closeMenu': { pt: 'Fechar menu', en: 'Close menu' },
  'common.socialNetworks': { pt: 'Redes sociais', en: 'Social networks' },
  'common.lgpdLaw': { pt: 'Lei Geral de Proteção de Dados (LGPD)', en: 'General Data Protection Law (LGPD)' },
  'common.brandLinks': { pt: 'Dashboard de Risco', en: 'Risk Dashboard' },
  'common.enterpriseNetworks': { pt: 'Para Redes e Franquias', en: 'For Networks and Franchises' },
  'common.riskDashboard': { pt: 'Dashboard de Risco', en: 'Risk Dashboard' },
  'common.assetsQr': { pt: 'Ativos & QR Code', en: 'Assets & QR Code' },
  'common.smartAlerts': { pt: 'Alertas Inteligentes', en: 'Smart Alerts' },
  'common.inspectionMode': { pt: 'Modo Fiscalização', en: 'Inspection Mode' },
  'common.digitalVault': { pt: 'Cofre Digital & OCR', en: 'Digital Vault & OCR' },
  'common.failureLogin': { pt: 'Falha ao entrar. Confira seus dados.', en: 'Sign-in failed. Check your details.' },
  'common.fillFields': { pt: 'Preencha todos os campos. A senha deve ter no mínimo 3 caracteres.', en: 'Fill in all fields. The password must be at least 3 characters.' },
  'common.passwordMismatch': { pt: 'As senhas não coincidem. Digite a mesma senha nos dois campos.', en: 'Passwords do not match. Type the same password in both fields.' },
  'common.createError': { pt: 'Não foi possível criar a conta.', en: 'Could not create the account.' },
  'common.demoName': { pt: 'Ex: Carlos Eduardo', en: 'E.g.: Alex Johnson' },
  'common.demoEmail': { pt: 'carlos@empresa.com.br', en: 'alex@company.com' },
  'common.demoPhone': { pt: '(11) 99999-8888', en: '(555) 999-8888' },
  'landing.oneClick': { pt: '1-CLIQUE', en: '1-CLICK' },

  // Estados e rótulos auxiliares
  'units.critical': { pt: 'Crítica', en: 'Critical' },
  'assets.maintenanceRegular': { pt: 'Em Dia', en: 'Up to Date' },
  'assets.maintenanceAttention': { pt: 'Revisão Próxima', en: 'Review Soon' },
  'assets.maintenanceUrgent': { pt: 'Urgente', en: 'Urgent' },
  'notif.levelInfo': { pt: 'Informativo', en: 'Informational' },
  'notif.levelWarning': { pt: 'Alerta Preventivo', en: 'Preventive Alert' },
  'notif.levelCritical': { pt: 'Crítico / Ação Imediata', en: 'Critical / Immediate Action' },
};

@Injectable({ providedIn: 'root' })
export class PreferenciasService {
  readonly idioma = signal<Idioma>('pt');

  constructor() {
    try {
      const lang = localStorage.getItem('licenfy-lang');
      if (lang === 'en' || lang === 'pt' || lang === 'es') this.idioma.set(lang);
    } catch { /* armazenamento indisponível */ }
    this.aplicarIdioma();
  }

  t(chave: string): string {
    const item = TRADUCOES[chave];
    if (!item) return chave;
    if (this.idioma() === 'es') return TRADUCOES_ES[chave] ?? item.en;
    return item[this.idioma()];
  }
  translate(key: string): string { return this.t(key); }

  /** Traduz valores de negócio que vengem dos dados mockados sem alterar os dados persistidos. */
  localizarTexto(valor: unknown): string {
    const texto = String(valor ?? '');
    if (!texto || this.idioma() === 'pt') return texto;

    const en: Record<string, string> = {
      'Alvará de Funcionamento e Localização': 'Operating and Location Permit',
      'AVCB - Auto de Vistoria do Corpo de Bombeiros': 'AVCB - Fire Department Inspection Report',
      'Licença Sanitária (CMVS)': 'Sanitary Permit (CMVS)',
      'Licença de Operação Ambiental (LO)': 'Environmental Operating Permit (LO)',
      'Laudo Técnico de Inspeção Predial e SPDA (Para-raios)': 'Technical Building Inspection and Lightning Protection Report',
      'Certificado de Conformidade Sanitária e Qualidade da Água': 'Sanitary Compliance and Water Quality Certificate',
      'Prefeitura Municipal de São Paulo': 'São Paulo City Hall',
      'Corpo de Bombeiros da PMESP': 'PMESP Fire Department',
      'Vigilância Sanitária Municipal (SMS Curitiba)': 'Municipal Health Surveillance (SMS Curitiba)',
      'Instituto Água e Terra (IAT Paraná)': 'Water and Land Institute (IAT Paraná)',
      'CREA-RJ / Engenharia Especializada': 'CREA-RJ / Specialized Engineering',
      'Subvisa Rio de Janeiro': 'Rio de Janeiro Health Department',
      'Matriz São Paulo': 'São Paulo Headquarters',
      'Filial Rio de Janeiro': 'Rio de Janeiro Branch',
      'Centro de Distribuição Curitiba': 'Curitiba Distribution Center',
      'CD Curitiba': 'Curitiba Distribution Center',
      'Bateria de Extintores e Hidrantes - Bloco A e B': 'Fire Extinguisher and Hydrant Battery - Blocks A and B',
      'Gerador de Emergência Stemac 180kVA': 'Stemac 180kVA Emergency Generator',
      'Gerador Diesel de Emergência Stemac 180kVA': 'Stemac 180kVA Diesel Emergency Generator',
      'Gerador Cummins 250kVA': 'Cummins 250kVA Generator',
      'Sistema de Climatização Central VRF Daikin 30HP': 'Daikin 30HP Central VRF Air Conditioning System',
      'Chiller de Refrigeração Industrial Trane 120TR': 'Trane 120TR Industrial Refrigeration Chiller',
      'Jurídico & Compliance': 'Legal & Compliance',
      'Operações RJ': 'Rio de Janeiro Operations',
      'Logística & Facilities': 'Logistics & Facilities',
      'Segurança do Trabalho': 'Occupational Safety',
      'Administrativo local': 'Local Administration',
      'Gestor da unidade': 'Unit Manager',
      'Gerente da unidade': 'Unit Manager',
      'Alvará': 'Permit',
      'Bombeiros': 'Fire Department',
      'Sanitária': 'Health',
      'Ambiental': 'Environmental',
      'Extintores': 'Fire Extinguishers',
      'Geradores': 'Generators',
      'Climatização': 'HVAC',
      'Preventiva': 'Preventive',
      'Corretiva': 'Corrective',
      'Recarga': 'Recharge',
      'Inspeção': 'Inspection',
      'Nenhum ativo direto': 'No direct asset',
      'Não informado': 'Not informed',
      'Sem registros': 'No records',
      'A programar': 'To be scheduled',
      'Localização a confirmar': 'Location to be confirmed',
      'Modelo a confirmar': 'Model to be confirmed',
      'Documento vigente': 'Current document',
      'Válida até': 'Valid until',
      'Conectado': 'Connected',
      'Em Dia': 'Up to Date',
      'Revisão Próxima': 'Review Soon',
      'Urgente': 'Urgent',
      'Regular': 'Regular',
      'Atenção': 'Attention',
      'Vigente': 'Current',
      'Em Renovação': 'Renewing',
      'Entregue': 'Delivered',
      'Lido': 'Read',
      'Ação Tomada': 'Action Taken'
    };

    const es: Record<string, string> = {
      ...en,
      'Alvará de Funcionamento e Localização': 'Permiso de funcionamiento y ubicación',
      'AVCB - Auto de Vistoria do Corpo de Bombeiros': 'AVCB - Informe de inspección del Cuerpo de Bomberos',
      'Licença Sanitária (CMVS)': 'Licencia sanitaria (CMVS)',
      'Licença de Operação Ambiental (LO)': 'Licencia de operación ambiental (LO)',
      'Laudo Técnico de Inspeção Predial e SPDA (Para-raios)': 'Informe técnico de inspección de edificios y SPDA (pararrayos)',
      'Certificado de Conformidade Sanitária e Qualidade da Água': 'Certificado de cumplimiento sanitario y calidad del agua',
      'Prefeitura Municipal de São Paulo': 'Ayuntamiento de São Paulo',
      'Corpo de Bombeiros da PMESP': 'Cuerpo de Bomberos de PMESP',
      'Vigilância Sanitária Municipal (SMS Curitiba)': 'Vigilancia sanitaria municipal (SMS Curitiba)',
      'Instituto Água e Terra (IAT Paraná)': 'Instituto de Agua y Tierra (IAT Paraná)',
      'CREA-RJ / Engenharia Especializada': 'CREA-RJ / Ingeniería especializada',
      'Subvisa Rio de Janeiro': 'Subvisa Río de Janeiro',
      'Matriz São Paulo': 'Sede São Paulo',
      'Filial Rio de Janeiro': 'Sucursal Río de Janeiro',
      'Centro de Distribuição Curitiba': 'Centro de distribución Curitiba',
      'CD Curitiba': 'Centro de distribución Curitiba',
      'Bateria de Extintores e Hidrantes - Bloco A e B': 'Batería de extintores e hidrantes - Bloques A y B',
      'Gerador de Emergência Stemac 180kVA': 'Generador de emergencia Stemac 180kVA',
      'Gerador Diesel de Emergência Stemac 180kVA': 'Generador diesel de emergencia Stemac 180kVA',
      'Gerador Cummins 250kVA': 'Generador Cummins 250kVA',
      'Sistema de Climatização Central VRF Daikin 30HP': 'Sistema central de climatización VRF Daikin 30HP',
      'Chiller de Refrigeração Industrial Trane 120TR': 'Chiller de refrigeración industrial Trane 120TR',
      'Jurídico & Compliance': 'Jurídico y cumplimiento',
      'Operações RJ': 'Operaciones RJ',
      'Logística & Facilities': 'Logística y facilities',
      'Segurança do Trabalho': 'Seguridad laboral',
      'Administrativo local': 'Administración local',
      'Gestor da unidade': 'Responsable de la unidad',
      'Alvará': 'Permiso',
      'Bombeiros': 'Bomberos',
      'Sanitária': 'Sanitaria',
      'Ambiental': 'Ambiental',
      'Extintores': 'Extintores',
      'Geradores': 'Generadores',
      'Climatização': 'Climatización',
      'Preventiva': 'Preventiva',
      'Corretiva': 'Correctiva',
      'Recarga': 'Recarga',
      'Inspeção': 'Inspección',
      'Nenhum ativo direto': 'Sin activo directo',
      'Não informado': 'No informado',
      'Sem registros': 'Sin registros',
      'A programar': 'Por programar',
      'Localização a confirmar': 'Ubicación por confirmar',
      'Modelo a confirmar': 'Modelo por confirmar',
      'Documento vigente': 'Documento vigente',
      'Conectado': 'Conectado',
      'Em Dia': 'Al día',
      'Revisão Próxima': 'Revisión próxima',
      'Urgente': 'Urgente',
      'Regular': 'Conforme',
      'Atenção': 'Atención',
      'Vigente': 'Vigente',
      'Em Renovação': 'En renovación',
      'Entregue': 'Entregado',
      'Lido': 'Leído',
      'Ação Tomada': 'Acción realizada'
    };

    const exact = this.idioma() === 'es' ? es[texto] : en[texto];
    if (exact) return exact;
    if (this.idioma() === 'es' && TRADUCOES_ES[texto]) return TRADUCOES_ES[texto];
    return texto;
  }

  localizeText(value: unknown): string { return this.localizarTexto(value); }

  statusClass(status: string | null | undefined): string {
    const value = String(status || '').toLowerCase();
    if (value === 'urgent' || value === 'urgente' || value === 'expiring' || value === 'vencendo') return 'urgent';
    if (value === 'attention' || value === 'atencao' || value === 'renew' || value === 'renovar em breve') return 'attention';
    if (value === 'regular' || value === 'valid' || value === 'current' || value === 'lido' || value === 'ação tomada' || value === 'entregue') return 'regular';
    return 'attention';
  }

  statusLabel(status: string | null | undefined): string {
    const value = String(status || '').toLowerCase();
    if (value === 'regular' || value === 'valid' || value === 'current') return this.t('status.current');
    if (value === 'attention' || value === 'atencao' || value === 'renew' || value === 'renovar em breve') return this.t('status.renew');
    if (value === 'urgent' || value === 'urgente' || value === 'expiring' || value === 'vencendo') return this.t('status.urgent');
    if (value === 'renewing' || value === 'em renovação') return this.t('status.renewing');
    if (value === 'critical' || value === 'crítica' || value === 'critica') return this.t('status.critical');
    if (value === 'lido') return this.t('status.read');
    if (value === 'ação tomada') return this.t('status.actionTaken');
    if (value === 'entregue') return this.t('status.delivered');
    return status || '';
  }

  alternarIdioma() {
    const proximos: Idioma[] = ['pt', 'en', 'es'];
    const atual = this.idioma();
    this.idioma.set(proximos[(proximos.indexOf(atual) + 1) % proximos.length]);
    this.aplicarIdioma();
    try { localStorage.setItem('licenfy-lang', this.idioma()); } catch { /* noop */ }
  }
  definirIdioma(idioma: Idioma) {
    this.idioma.set(idioma);
    this.aplicarIdioma();
    try { localStorage.setItem('licenfy-lang', idioma); } catch { /* noop */ }
  }
  setLanguage(idioma: Idioma) { this.definirIdioma(idioma); }
  toggleLanguage() { this.alternarIdioma(); }

  private aplicarIdioma() {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = this.idioma() === 'pt' ? 'pt-BR' : this.idioma();
    }
  }
}

export const PreferencesService = PreferenciasService;
