export const TRADUCOES_ES: Record<string, string> = {
  'header.toES': 'Cambiar a español',
  'header.toEN': 'Cambiar a English',
  'header.toPT': 'Cambiar a Português',
  'header.signin': 'Iniciar sesión',
  'header.bookDemo': 'Solicita una demo',
  'nav.platform': 'Plataforma',
  'nav.solutions': 'Soluciones',
  'nav.industries': 'Industrias',
  'nav.modules': 'Módulos',
  'nav.features': 'Funciones',
  'nav.pricing': 'Planes',
  'shell.modules': 'Módulos del sistema',
  'shell.dashboard': 'Dashboard',
  'shell.units': 'Unidades y responsables',
  'shell.vault': 'Bóveda digital y OCR',
  'shell.assets': 'Gestión de activos y QR',
  'shell.alerts': 'Alertas inteligentes',
  'shell.inspection': 'Modo inspección',
  'shell.roi': 'Informe de ROI',
  'shell.operational': 'Licenfy Operacional',
  'shell.allUnits': 'Todas las unidades',
  'shell.inspectionBtn': 'Inspección',
  'shell.logoutBtn': 'Salir',
  'shell.unitsShort': 'Unidades y jerarquía',
  'auth.back': 'Volver al sitio',
  'auth.loginTab': 'Entrar con una cuenta existente',
  'auth.signupTab': 'Probar / Crear cuenta',
  'auth.welcomeBack': 'BIENVENIDO DE NUEVO',
  'auth.loginTitle': 'Inicia sesión en tu cuenta',
  'auth.loginSub': 'Accede al panel de tu empresa con tu cuenta existente.',
  'auth.email': 'Correo corporativo',
  'auth.password': 'Contraseña',
  'auth.loginBtn': 'Entrar a la plataforma',
  'auth.authenticating': 'Autenticando...',
  'auth.forgot': 'Olvidé mi contraseña',
  'auth.noAccount': '¿Aún no tienes una cuenta?',
  'auth.seePlans': 'Conoce nuestros planes y suscríbete',
  'auth.createTest': 'Crea una cuenta de prueba',
  'auth.getStarted': 'EMPIEZA AHORA',
  'auth.signupTitle': 'Crea tu cuenta de prueba',
  'auth.signupSub': 'Prueba Licenfy de inmediato, sin necesidad de base de datos.',
  'auth.name': 'Nombre completo',
  'auth.createPass': 'Crea una contraseña',
  'auth.confirmPass': 'Confirma tu contraseña',
  'auth.signupBtn': 'Crear cuenta y acceder a la plataforma',
  'auth.haveAccount': '¿Ya tienes una cuenta?',
  'auth.signinLink': 'Iniciar sesión',
  'auth.lgpd': 'He leído y acepto los Términos de Uso y la Política de Privacidad, y autorizo el tratamiento de mis datos conforme a la LGPD (Ley n.º 13.709/2018).',
  'auth.needLogin': 'Para entrar, debes aceptar los Términos de Uso y la Política de Privacidad (LGPD).',
  'auth.needSignup': 'Para crear la cuenta, debes aceptar los Términos de Uso y la Política de Privacidad (LGPD).',
  'auth.brandKicker': 'PLATAFORMA DE CUMPLIMIENTO',
  'auth.brandTitle': 'Control total, sin frenar el ritmo del día a día.',
  'auth.brandDesc': 'Documentos, plazos, activos y responsables en un solo lugar.',
  'auth.brandPoint1': 'Acceso seguro para tu equipo',
  'auth.brandPoint2': 'Alertas e historial auditable',
  'auth.brandPoint3': 'Visión consolidada por unidad',
  'auth.brandPoint4': 'Entorno de prueba con datos de ejemplo',
  'auth.emailPlaceholder': 'tu@empresa.com',
  'auth.passwordPlaceholder': 'Tu contraseña',
  'auth.namePlaceholder': 'Ej.: Carlos Eduardo',
  'auth.minPassword': 'Mínimo 3 caracteres',
  'auth.repeatPassword': 'Repite la contraseña creada',
  'landing.heroKicker': 'CUMPLIMIENTO OPERATIVO EN TIEMPO REAL',
  'landing.heroTitle': 'Nunca más sufra un cierre por un permiso vencido sin aviso',
  'landing.heroSub': 'Licenfy centraliza tus licencias, permisos y activos con monitoreo continuo y alertas por correo corporativo que escalan desde el equipo local hasta la dirección.',
  'landing.trust1': 'Cero riesgo de cierre en las sucursales',
  'landing.trust2': 'OCR de permisos en PDF: objetivo de precisión superior al 99 %',
  'landing.trust3': 'Listo para redes de 1 a más de 100 unidades',
  'landing.platformKicker': 'PLATAFORMA LICENFY',
  'landing.platformTitle': 'Una sola visión para cada plazo, documento y activo.',
  'landing.platformSub': 'Sustituye archivos dispersos y hojas de cálculo manuales por una operación conectada, con contexto por unidad e historial listo para auditorías.',
  'landing.solKicker': 'SOLUCIONES PARA TU OPERACIÓN',
  'landing.solutionsTitle': 'Control que acompaña el ritmo de tu negocio.',
  'landing.plansKicker': 'PLANES',
  'landing.plansTitle': 'Un plan sencillo para cada ritmo de operación',
  'landing.plansSub': 'Sin cuota de implantación. Cancela cuando quieras en el mensual. En el anual, ahorras un 50 %.',
  'landing.monthly': 'Mensual',
  'landing.annual': 'Anual',
  'landing.roiBadge': 'RETORNO DE LA INVERSIÓN',
  'landing.roiTitle': 'El coste de un solo cierre paga 10 años de Licenfy',
  'landing.platformPoint1Title': 'Operación conectada',
  'landing.platformPoint1Desc': 'Licencias, personas y activos en un mismo flujo.',
  'landing.platformPoint2Title': 'Visión por unidad',
  'landing.platformPoint2Desc': 'Prioriza la acción correcta en cada sucursal.',
  'landing.platformPoint3Title': 'Historial auditable',
  'landing.platformPoint3Desc': 'Decisiones y documentos siempre trazables.',
  'landing.solution1Title': 'Redes y franquicias',
  'landing.solution1Desc': 'Estandariza el cumplimiento de cada unidad sin sobrecargar al equipo central.',
  'landing.solution2Title': 'Jurídico y cumplimiento',
  'landing.solution2Desc': 'Anticipa riesgos y mantiene evidencias organizadas para inspecciones.',
  'landing.solution3Title': 'Facilities y operaciones',
  'landing.solution3Desc': 'Conecta obligaciones regulatorias con el mantenimiento de los activos físicos.',
  'landing.industriesTitle': 'Licenfy atiende a diversos sectores',
  'landing.industry1': 'Industria ligera',
  'landing.industry1Desc': 'Medio ambiente, activos y mantenimiento',
  'landing.industry2': 'Salud',
  'landing.industry2Desc': 'Farmacias y clínicas',
  'landing.industry3': 'Comercio multitienda',
  'landing.industry3Desc': 'Redes de 5 a 50 unidades',
  'landing.industry4': 'Alimentación',
  'landing.industry4Desc': 'Restaurantes y servicios de alimentación',
  'landing.featuresTitle': 'Del archivador al control absoluto en 4 pilares',
  'landing.featuresSub': 'Se acabaron las hojas de cálculo olvidadas, las multas municipales y las sorpresas durante una inspección.',
  'landing.feature1Title': 'Bóveda digital y OCR automatizado',
  'landing.feature1Desc': 'Solo arrastra el PDF del permiso. El sistema OCR lee y cataloga automáticamente el organismo emisor, las fechas de emisión y vencimiento y los requisitos técnicos.',
  'landing.feature1Cta': 'Explorar la bóveda digital',
  'landing.feature2Title': 'Modo inspección',
  'landing.feature2Desc': '¿El inspector municipal o de bomberos llegó sin aviso? En un clic genera el dosier oficial consolidado con QR público de autenticidad.',
  'landing.feature2Cta': 'Ver el dosier en acción',
  'landing.feature3Title': 'Activos físicos con QR Code',
  'landing.feature3Desc': 'Genera etiquetas para extintores, ascensores, generadores y aire acondicionado. El equipo local escanea con el móvil y consulta la recarga sin iniciar sesión.',
  'landing.feature3Cta': 'Ver gestión de activos',
  'landing.feature4Title': 'Alertas inteligentes',
  'landing.feature4Desc': 'Envía alertas automáticas por correo al responsable de la unidad, propietarios y dirección con 90, 60 y 30 días de antelación. Garantiza gobernanza con un rastro de auditoría.',
  'landing.feature4Cta': 'Configurar alertas',
  'landing.resourcesKicker': 'FUNCIONES',
  'landing.resourcesTitle': 'Información lista cuando la operación necesita actuar.',
  'landing.resourcesSub': 'Más previsibilidad para decisiones diarias y respuestas rápidas en cualquier escenario.',
  'landing.resource1Title': 'Lectura de documentos con OCR',
  'landing.resource1Desc': 'Extracción automática de campos y fechas de validez.',
  'landing.resource2Title': 'Alertas escalonadas',
  'landing.resource2Desc': 'Notificaciones por plazo para las personas responsables.',
  'landing.resource3Title': 'QR Code para activos',
  'landing.resource3Desc': 'Consulta inmediata del estado en el lugar de la operación.',
  'landing.roiSubtitle': 'Las empresas que utilizan Licenfy reducen a cero el índice de multas y ahorran miles de horas de trabajo jurídico y de facilities.',
  'landing.roiLabel1': 'Ahorro acumulado generado en la plataforma',
  'landing.roiLabel2': 'Infracciones pendientes en las unidades monitorizadas',
  'landing.roiLabel3': 'Puntuación media de cumplimiento en las unidades monitorizadas',
  'landing.monthlyHeadline': 'Flexibilidad mes a mes',
  'landing.monthlyDesc': 'Ideal para validar Licenfy en unas pocas unidades y expandirse a tu ritmo.',
  'landing.monthlyNote': 'Facturación mensual recurrente. Sin permanencia.',
  'landing.monthlyFeature1': 'Licencias, permisos y activos ilimitados',
  'landing.monthlyFeature2': 'OCR de PDF con extracción automática',
  'landing.monthlyFeature3': 'Alertas por correo a 90, 60 y 30 días',
  'landing.monthlyFeature4': 'QR Code para activos y modo inspección',
  'landing.monthlyCta': 'Empezar con el mensual',
  'landing.saveTag': 'AHORRA UN 50 %',
  'landing.annualHeadline': 'Mejor relación calidad-precio',
  'landing.annualDesc': 'Para operaciones que buscan previsibilidad y el máximo ahorro todo el año.',
  'landing.annualNote': 'Equivale a',
  'landing.annualNoteStrong': 'R$ 100/mes',
  'landing.annualNoteRest': '— 12 meses por el precio de 6.',
  'landing.annualFeature1': 'Todo lo incluido en el plan mensual',
  'landing.annualFeature2': '2 meses de prioridad en soporte',
  'landing.annualFeature3': 'Informe ejecutivo de cumplimiento',
  'landing.annualFeature4': 'Incorporación asistida de las unidades',
  'landing.annualCta': 'Suscribirse al plan anual',
  'landing.footerKicker': 'CUMPLIMIENTO EN MOVIMIENTO',
  'landing.footerTitle': 'Control total. Empieza ahora.',
  'landing.footerSub': 'Convierte licencias, permisos y activos en una operación segura y predecible.',
  'landing.footerDesc': 'La plataforma definitiva de cumplimiento regulatorio, gestión de permisos y activos con tecnología avanzada para empresas medianas y grandes.',
  'landing.encryption': 'Cifrado bancario',
  'landing.contact': 'Contacto y demostración',
  'landing.scheduleConsultant': 'Concertar con un consultor',
  'landing.terms': 'Términos de uso',
  'landing.privacy': 'Política de privacidad',
  'landing.security': 'Seguridad de la información',
  'landing.rights': '© 2026 Licenfy Tecnologia S.A. Todos los derechos reservados.',
  'landing.modalTitle': 'Solicita una demostración personalizada',
  'landing.modalIntro': 'Descubre cómo Licenfy elimina el riesgo de multas y cierres en tus sucursales con inteligencia artificial y OCR.',
  'landing.modalName': 'Tu nombre completo',
  'landing.modalEmail': 'Correo corporativo',
  'landing.modalPhone': 'Teléfono corporativo',
  'landing.modalUnits': 'Número de sucursales / unidades',
  'landing.modalUnits1': 'De 1 a 5 sucursales',
  'landing.modalUnits2': 'De 6 a 20 sucursales',
  'landing.modalUnits3': 'De 21 a 50 sucursales',
  'landing.modalUnits4': 'Más de 50 sucursales',
  'landing.modalSubmit': 'Concertar con un especialista',
  'landing.modalSandbox': 'Entrar al sistema directo (Sandbox)',
  'dashboard.desc': 'Monitoreo preventivo de permisos, licencias ambientales, inspecciones y garantías de activos.',
  'dashboard.alertAria': '1 alerta de mantenimiento vinculada',
  'dashboard.alertTitle': 'Mantenimiento vinculado',
  'dashboard.alertText': 'El AVCB vence en 25 días',
  'dashboard.alertDesc': 'La renovación depende de la recarga y la inspección de la batería de extintores (EQ-0199).',
  'dashboard.viewAsset': 'Ver activo vinculado',
  'dashboard.upload': 'Subir licencia',
  'dashboard.dossier': 'Dosier de inspección',
  'dashboard.filterUnit': 'Filtrar unidad:',
  'dashboard.allUnits': 'Todas las unidades (visión consolidada)',
  'dashboard.scoreCaption': 'Índice general de cumplimiento',
  'dashboard.scoreTitle': 'Puntuación de cumplimiento',
  'dashboard.compliance': 'Cumplimiento',
  'dashboard.validLicenses': 'Licencias válidas',
  'dashboard.renewSoon': 'Renovación próxima (< 30 d)',
  'dashboard.criticalRisk': 'Riesgo crítico / inminente',
  'dashboard.zeroFines': 'Cero multas en los últimos 12 meses en las sucursales monitorizadas.',
  'dashboard.regularDocs': 'Documentos y licencias al día',
  'dashboard.regularDocsDesc': 'Sin pendientes legales ni de organismos inspectores.',
  'dashboard.attentionDocs': 'Plazos en cuenta atrás',
  'dashboard.attentionDocsDesc': 'Alertas en curso (de 30 a 60 días).',
  'dashboard.urgentDocs': 'Riesgo inminente o pendiente crítico',
  'dashboard.urgentDocsDesc': 'Se recomienda una acción inmediata para evitar una infracción.',
  'dashboard.monitoringTitle': 'Monitoreo activo de obligaciones',
  'dashboard.monitoringSub': 'Permisos, licencias ambientales, sanitarias e inspecciones bajo gestión continua',
  'dashboard.accessVault': 'Acceder a la bóveda digital',
  'dashboard.status': 'Estado',
  'dashboard.document': 'Documento / obligación',
  'dashboard.issuer': 'Organismo emisor',
  'dashboard.unitBranch': 'Unidad / sucursal',
  'dashboard.expiration': 'Vencimiento',
  'dashboard.linkedAsset': 'Activo vinculado',
  'dashboard.preventiveAction': 'Acción preventiva',
  'dashboard.daysRemaining': 'días restantes',
  'dashboard.noLink': 'Sin vínculo directo',
  'dashboard.emailSent': '¡Correo enviado!',
  'dashboard.alertEmail': 'Alertar por correo',
  'status.regular': 'Conforme',
  'status.attention': 'Atención',
  'status.urgent': 'Urgente',
  'status.valid': 'Válido',
  'status.renew': 'Renovar pronto',
  'status.expiring': 'Vencimiento próximo',
  'status.current': 'Vigente',
  'status.renewing': 'En renovación',
  'status.delivered': 'Entregado',
  'status.critical': 'Crítico',
  'status.read': 'Leído',
  'status.actionTaken': 'Acción realizada',
  'status.currentShort': 'Actual',
  'units.structure': 'Estructura de la operación',
  'units.desc': 'Organiza la red como empresa → unidad → documentos y activos, sin concentrar el conocimiento en una sola persona.',
  'units.new': 'Nueva unidad',
  'units.active': 'unidades activas',
  'units.docsAssets': 'documentos y activos por unidad',
  'units.network': 'Red de unidades',
  'units.registered': 'registradas',
  'units.selected': 'UNIDAD SELECCIONADA',
  'units.address': 'Dirección',
  'units.documents': 'Documentos',
  'units.managedDocs': 'documentos bajo gestión',
  'units.assets': 'Activos',
  'units.linkedAssets': 'activos vinculados',
  'units.responsible': 'Responsables y destinatarios',
  'units.responsibleDesc': 'Todos reciben alertas automáticas según la unidad.',
  'units.addResponsible': 'Añadir responsable',
  'units.primary': 'Principal',
  'units.formKicker': 'REGISTRO DE SUCURSAL',
  'units.formTitle': 'Nueva unidad',
  'units.name': 'Nombre de la unidad',
  'units.city': 'Ciudad',
  'units.state': 'UF',
  'units.manager': 'Responsable',
  'units.managerEmail': 'Correo del responsable',
  'units.phone': 'Teléfono corporativo',
  'units.critical': 'Crítica',
  'common.cancel': 'Cancelar',
  'common.saveUnit': 'Guardar unidad',
  'common.close': 'Cerrar',
  'common.add': 'Añadir',
  'common.days': 'días',
  'common.view': 'Visualizar',
  'common.pdf': 'Ver PDF',
  'vault.kicker': 'Bóveda digital cifrada y lectura automática',
  'vault.desc': 'Centraliza todos los PDF, facturas y permisos. El sistema lee la información y completa las fechas automáticamente.',
  'vault.ocrTitle': 'Área de carga y escaneo OCR',
  'vault.ocrDesc': 'Arrastra documentos PDF o elige un ejemplo oficial para simular la extracción automática de datos.',
  'vault.secureRead': 'Lectura segura de documentos',
  'vault.secureReadDesc': 'los datos se extraen y verifican en la bóveda de la empresa.',
  'vault.dropTitle': 'Arrastra aquí tu PDF o imagen',
  'vault.dropDesc': 'Compatible con PDF, JPG y PNG (hasta 4 MB)',
  'vault.selectFile': 'Seleccionar archivo del ordenador',
  'vault.processing': 'Procesando documento...',
  'vault.success': '¡Lectura del documento completada correctamente!',
  'vault.successDesc': 'Revisa los campos completados automáticamente antes de archivarlos en la bóveda.',
  'vault.sample': 'Usar ejemplo simulado',
  'vault.extracted': 'Confirmación de datos extraídos',
  'vault.review': 'Revisión de datos.',
  'vault.reviewDesc': 'Comprueba organismo emisor, fechas, valor y unidad antes de guardar en el sistema.',
  'vault.obligation': 'Título de la obligación / licencia',
  'vault.issuer': 'Organismo emisor',
  'vault.category': 'Categoría jurídica',
  'vault.protocol': 'Número de registro / protocolo',
  'vault.unit': 'Unidad / sucursal',
  'vault.issueDate': 'Fecha de emisión',
  'vault.expiryDate': 'Fecha de vencimiento oficial',
  'vault.fineEstimate': 'Estimación de multa si no se renueva (R$)',
  'vault.linkedAsset': 'Activo físico vinculado (opcional)',
  'vault.validationNotes': 'Notas de validación OCR',
  'vault.confirmArchive': 'Confirmar datos y archivar',
  'vault.documents': 'Documentos y licencias en la bóveda digital',
  'vault.indexed': 'documentos indexados y protegidos',
  'vault.searchPlaceholder': 'Buscar por licencia, organismo o número...',
  'vault.allCategories': 'Todas las categorías',
  'vault.viewDoc': 'Visualizar documento',
  'vault.versions': 'Versiones',
  'vault.historyKicker': 'HISTORIAL INMUTABLE',
  'vault.historyDesc': 'Las renovaciones anteriores se conservan y nunca sustituyen la versión archivada.',
  'vault.currentVersion': 'Versión actual',
  'vault.previousVersion': 'Versión anterior',
  'vault.archived': 'Archivada',
  'vault.confirmedVault': 'confirmado en la bóveda',
  'vault.auditPreserved': 'Archivo conservado para auditoría y trazabilidad',
  'vault.categoryPermit': 'Permiso de funcionamiento',
  'vault.categoryFire': 'Bomberos / AVCB',
  'vault.categoryHealth': 'Inspección sanitaria',
  'vault.categoryEnvironmental': 'Licenciamiento ambiental',
  'vault.categorySafety': 'Seguridad laboral / NR',
  'vault.categoryPermits': 'Permisos',
  'vault.categoryFireShort': 'Bomberos / AVCB',
  'vault.categoryHealthShort': 'Sanitaria',
  'vault.categoryEnvironmentalShort': 'Ambiental',
  'vault.categorySafetyShort': 'Seguridad laboral',
  'vault.expiry': 'Vencimiento',
  'vault.days': 'días',
  'vault.closeHistory': 'Cerrar historial',
  'assets.kicker': 'Operación en el punto de uso sin aplicación',
  'assets.desc': 'Etiquetas físicas aplicadas a los equipos. Al escanear con el móvil, cualquier colaborador accede a garantías, mantenimientos y facturas.',
  'assets.register': 'Registrar activo',
  'assets.modalTitle': 'Nuevo activo y etiqueta QR',
  'assets.modalDesc': 'Registra el equipo y vincula la factura para seguir la garantía y el mantenimiento.',
  'assets.equipmentName': 'Nombre del equipo',
  'assets.assetTag': 'Etiqueta patrimonial',
  'assets.unit': 'Unidad',
  'assets.invoice': 'Factura',
  'assets.warrantyUntil': 'Garantía hasta',
  'assets.saveQr': 'Guardar y generar QR',
  'assets.all': 'Todos los activos',
  'assets.extinguishers': 'Extintores y AVCB',
  'assets.generators': 'Generadores',
  'assets.hvac': 'Climatización y enfriadores',
  'assets.upToDate': 'Al día',
  'assets.reviewSoon': 'Revisión próxima',
  'assets.urgent': 'Urgente',
  'assets.location': 'Ubicación:',
  'assets.warranty': 'Garantía del fabricante:',
  'assets.unification': 'Unificación legal y operativa',
  'assets.lastIntervention': 'Última intervención:',
  'assets.maintenanceCount': 'mantenimientos registrados',
  'assets.qrLabel': 'Etiqueta QR Code',
  'assets.operatorView': 'Visión del operador',
  'assets.physicalTitle': 'Etiqueta física con QR Code patrimonial',
  'assets.physicalDesc': 'Etiqueta lista para aplicarse directamente al equipo. El QR permite consultar al instante desde el navegador del móvil sin instalar aplicaciones.',
  'assets.scanCamera': 'Apunta la cámara',
  'assets.assetProperty': 'PATRIMONIO',
  'assets.warrantyLabel': 'Garantía hasta:',
  'assets.operationalManagement': 'GESTIÓN OPERACIONAL LICENFY',
  'assets.downloadQr': 'Descargar QR en PNG',
  'assets.printLabel': 'Imprimir etiqueta adhesiva',
  'assets.simulatorTitle': 'Simulador: visión del operador en el lugar',
  'assets.connected': 'Conectado',
  'assets.warrantyActive': 'Garantía vigente',
  'assets.validUntil': 'Válida hasta',
  'assets.remainingDays': 'días restantes',
  'assets.purchaseInvoice': 'Factura de compra:',
  'assets.interventionHistory': 'Historial de intervenciones',
  'assets.technician': 'Técnico:',
  'assets.reportIssue': 'Informar incidencia / activar garantía',
  'assets.issueRegistered': '¡Solicitud registrada correctamente!',
  'assets.howWorks': '¿Cómo funciona en la práctica?',
  'assets.howWorksDesc': 'El técnico apunta la cámara del móvil a la etiqueta física pegada en la máquina.',
  'assets.directAccess': 'Acceso directo:',
  'assets.directAccessDesc': 'No requiere descargar una aplicación.',
  'assets.savesCosts': 'Ahorra costes:',
  'assets.savesCostsDesc': 'Consulta al instante si la pieza sigue cubierta por la garantía de la factura.',
  'assets.traceability': 'Trazabilidad:',
  'assets.traceabilityDesc': 'Historial de revisiones preventivas actualizado en tiempo real.',
  'assets.maintenanceRegular': 'Al día',
  'assets.maintenanceAttention': 'Revisión próxima',
  'assets.maintenanceUrgent': 'Urgente',
  'notif.kicker': 'Comunicación corporativa y rastro de auditoría',
  'notif.rulesTitle': 'Alertas de disparo corporativo',
  'notif.rulesSub': 'Disparadores automáticos configurados antes de cualquier vencimiento',
  'notif.daysBefore': 'días antes',
  'notif.infoLevel': 'Informativo',
  'notif.preventiveLevel': 'Alerta preventiva',
  'notif.criticalLevel': 'Crítico / acción inmediata',
  'notif.customTitle': 'Añadir alerta personalizada',
  'notif.customDesc': 'Define plazos y destinatarios específicos para tu empresa.',
  'notif.recipientsPlaceholder': 'Correos corporativos separados por comas',
  'notif.simulateTitle': 'Simular envío inmediato de correo de alerta',
  'notif.sending': 'Enviando...',
  'notif.sendTest': 'Enviar prueba',
  'notif.success': '¡Correo corporativo enviado y registrado en el historial de auditoría!',
  'notif.logsTitle': 'Historial de envíos de correo (auditoría corporativa)',
  'notif.logsSub': 'Rastro de auditoría legal con fecha, hora, destinatario y estado de entrega de cada alerta',
  'notif.channel': 'Canal',
  'notif.dateTime': 'Fecha / hora',
  'notif.recipient': 'Destinatario',
  'notif.documentAsset': 'Documento / activo',
  'notif.advance': 'Antelación',
  'notif.deliveryStatus': 'Estado de entrega',
  'notif.preview': 'Vista previa del correo',
  'notif.levelInfo': 'Informativo',
  'notif.levelWarning': 'Alerta preventiva',
  'notif.levelCritical': 'Crítico / acción inmediata',
  'inspection.kicker': 'Modo inspección inmediata',
  'inspection.desc': 'Compilación instantánea de todos los permisos, informes y licencias vigentes, lista para auditorías externas e inspectores.',
  'inspection.unit': 'Unidad a inspeccionar:',
  'inspection.print': 'Imprimir / exportar PDF del dosier',
  'inspection.included': 'Documentos incluidos',
  'inspection.includedDesc': 'Selecciona lo que se consolidará en el PDF.',
  'inspection.platformCaption': 'PLATAFORMA INTEGRADA DE CUMPLIMIENTO Y REGULARIDAD OPERACIONAL',
  'inspection.certificate': 'CERTIFICADO DIGITAL DE CUMPLIMIENTO',
  'inspection.issued': 'Emisión:',
  'inspection.authentication': 'Autenticación:',
  'inspection.generalStatus': 'Estado general:',
  'inspection.audited': 'CONFORME Y AUDITADO',
  'inspection.company': 'Razón social / sucursal',
  'inspection.cnpj': 'CNPJ oficial',
  'inspection.cityState': 'Municipio / UF',
  'inspection.legalOwner': 'Responsable legal / jurídico',
  'inspection.score': 'Puntuación de cumplimiento',
  'inspection.validLicenses': 'Licencias válidas adjuntas',
  'inspection.inspectedAssets': 'Activos físicos inspeccionados',
  'inspection.pendingViolations': 'Infracciones pendientes',
  'inspection.section1': '1. Relación oficial de permisos, licencias e informes técnicos',
  'inspection.document': 'Documento / obligación',
  'inspection.issuingBody': 'Organismo emisor',
  'inspection.registration': 'N.º de registro / protocolo',
  'inspection.issueDate': 'Fecha de emisión',
  'inspection.officialValidity': 'Validez oficial',
  'inspection.legalStatus': 'Estado legal',
  'inspection.section2': '2. Certificación de mantenimiento preventivo de los activos de seguridad',
  'inspection.maintenanceDesc': 'Todos los equipos críticos vinculados a licencias municipales y estatales tienen un plan de mantenimiento preventivo continuo y etiquetas patrimoniales con QR Code registradas en la plataforma:',
  'inspection.fireTitle': 'Sistemas de prevención y extinción de incendios',
  'inspection.fireExtinguishers': 'Recarga de extintores:',
  'inspection.fireExtinguishersDesc': 'Prueba hidrostática y anillos de identificación actualizados.',
  'inspection.hydrants': 'Presurización de hidrantes:',
  'inspection.hydrantsDesc': 'Válvulas y mangueras con informe de prueba estanca.',
  'inspection.electricalTitle': 'Instalaciones eléctricas y SPDA (pararrayos)',
  'inspection.nr10': 'Informe NR-10:',
  'inspection.nr10Desc': 'Termografía de paneles y puesta a tierra conformes a la normativa.',
  'inspection.generators': 'Generadores de emergencia:',
  'inspection.generatorsDesc': 'Batería de pruebas de arranque quincenales registrada.',
  'inspection.complianceManager': 'Responsable de cumplimiento y operaciones',
  'inspection.digitalSignature': 'Firma digital ICP-Brasil estándar PAdES',
  'inspection.issuedSecure': 'Dosier emitido en un entorno seguro por la plataforma Licenfy. Código público de validación:',
  'inspection.validAuditors': 'Documento válido para mostrar a auditores y autoridades públicas inspectoras.',
  'inspection.historyTitle': 'Historial de dosieres generados',
  'inspection.historyDesc': 'Trazabilidad de todas las exportaciones por unidad.',
  'inspection.documentsCount': 'documentos',
  'roi.kicker': 'Retorno financiero medible',
  'roi.desc': 'Panel ejecutivo que contabiliza el ahorro generado al activar garantías a tiempo y evitar multas regulatorias y paradas.',
  'roi.totalLabel': 'AHORRO TOTAL ACUMULADO POR LA PLATAFORMA',
  'roi.totalDesc': 'Ganancias auditadas que combinan multas evitadas, piezas en garantía activadas y horas operativas reducidas en las sucursales.',
  'roi.multiplier': 'Multiplicador de ROI',
  'roi.netReturn': 'Retorno neto',
  'roi.hoursSaved': 'Horas ahorradas',
  'roi.legalPrevention': 'Prevención legal',
  'roi.finesAvoided': 'Multas regulatorias evitadas',
  'roi.finesDesc': 'Valor calculado según las tablas de infracción de organismos (ayuntamientos, bomberos, ANVISA y organismos ambientales).',
  'roi.assetManagement': 'Gestión de activos',
  'roi.warrantyParts': 'Piezas y reparaciones en garantía',
  'roi.warrantyDesc': 'Servicios y cambios de componentes realizados sin coste consultando la factura y la vigencia mediante QR Code.',
  'roi.efficiency': 'Eficiencia B2B',
  'roi.teamTime': 'Tiempo de equipo optimizado',
  'roi.teamTimeDesc': 'Eliminación de hojas de cálculo manuales y Introducing bureaucratic data through OCR and automatic alerts.',
  'roi.preventedTitle': 'Infracciones y multas evitadas',
  'roi.preventedDesc': 'Obligaciones renovadas dentro del plazo antes de la infracción',
  'roi.obligation': 'Obligación / licencia',
  'roi.body': 'Organismo',
  'roi.branch': 'Sucursal',
  'roi.fineAvoided': 'Multa evitada',
  'roi.warrantyTitle': 'Garantías de activos activadas a tiempo',
  'roi.warrantySavingsDesc': 'Ahorro en mantenimientos cubiertos por el fabricante',
  'roi.equipment': 'Equipo',
  'roi.partService': 'Componente / servicio',
  'roi.date': 'Fecha',
  'roi.savings': 'Ahorro generado',
  'assetPage.identified': 'ACTIVO IDENTIFICADO',
  'assetPage.notFound': 'ACTIVO NO ENCONTRADO',
  'assetPage.property': 'Patrimonio:',
  'assetPage.unit': 'Unidad',
  'assetPage.location': 'Ubicación',
  'assetPage.nextMaintenance': 'Próximo mantenimiento',
  'assetPage.notFoundText': 'Este QR Code no corresponde a un activo disponible.',
  'assetPage.notFoundDesc': 'Comprueba la etiqueta o contacta con el equipo responsable.',
  'assetPage.go': 'Ir a Licenfy',
  'common.brand': 'Licenfy Tecnología',
  'common.seePlans': 'Conoce nuestros planes y suscríbete',
  'common.notifications': 'Notificaciones recientes',
  'common.openMenu': 'Abrir o cerrar el menú de módulos',
  'common.openMobileMenu': 'Abrir menú de módulos',
  'common.closeMenu': 'Cerrar menú',
  'common.socialNetworks': 'Redes sociales',
  'common.lgpdLaw': 'Ley General de Protección de Datos (LGPD)',
  'common.riskDashboard': 'Dashboard de riesgos',
  'common.enterpriseNetworks': 'Para redes y franquicias',
  'common.assetsQr': 'Activos y QR Code',
  'common.smartAlerts': 'Alertas inteligentes',
  'common.inspectionMode': 'Modo inspección',
  'common.digitalVault': 'Bóveda digital y OCR',
  'common.failureLogin': 'Error al iniciar sesión. Comprueba tus datos.',
  'common.fillFields': 'Completa todos los campos. La contraseña debe tener al menos 3 caracteres.',
  'common.passwordMismatch': 'Las contraseñas no coinciden. Escribe la misma contraseña en ambos campos.',
  'common.createError': 'No se pudo crear la cuenta.',
  'common.demoName': 'Ej.: Carlos Eduardo',
  'common.demoEmail': 'carlos@empresa.com',
  'common.demoPhone': '(555) 999-8888',
  'landing.oneClick': '1 CLIC',
};
